// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com.ctrip.flight.agg.shopping.contract.transportation.response.proto

package com.ctrip.flight.agg.shopping.contract.transportation.response;

public interface DiffServiceTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ctrip.flight.agg.shopping.contract.transportation.response.DiffServiceType)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 产品类型，高返，快速出票，X产品等
   * </pre>
   *
   * <code>string UpsellProductType = 1;</code>
   */
  java.lang.String getUpsellProductType();
  /**
   * <pre>
   * 产品类型，高返，快速出票，X产品等
   * </pre>
   *
   * <code>string UpsellProductType = 1;</code>
   */
  com.google.protobuf.ByteString
      getUpsellProductTypeBytes();
}
