// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com.ctrip.flight.agg.shopping.contract.transportation.response.proto

package com.ctrip.flight.agg.shopping.contract.transportation.response;

public interface FlightProductBookingSceneTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ctrip.flight.agg.shopping.contract.transportation.response.FlightProductBookingSceneType)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 索引号
   * </pre>
   *
   * <code>int32 RefNum = 1;</code>
   */
  int getRefNum();

  /**
   * <pre>
   **
   *对应原DeprecatedInfo 作为待废弃兼容实体的替换
   *Key：ProductType,PolicyID,PolicyCategory,PolicyType,LateCostPrice,ShareNormalPolicyID,PreAdjustPrice,OriginalPolicyType,CostRate,PackageOption,IsBooking,TransitType
   * </pre>
   *
   * <code>repeated .com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType DeprecatedTag = 2;</code>
   */
  java.util.List<com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType> 
      getDeprecatedTagList();
  /**
   * <pre>
   **
   *对应原DeprecatedInfo 作为待废弃兼容实体的替换
   *Key：ProductType,PolicyID,PolicyCategory,PolicyType,LateCostPrice,ShareNormalPolicyID,PreAdjustPrice,OriginalPolicyType,CostRate,PackageOption,IsBooking,TransitType
   * </pre>
   *
   * <code>repeated .com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType DeprecatedTag = 2;</code>
   */
  com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType getDeprecatedTag(int index);
  /**
   * <pre>
   **
   *对应原DeprecatedInfo 作为待废弃兼容实体的替换
   *Key：ProductType,PolicyID,PolicyCategory,PolicyType,LateCostPrice,ShareNormalPolicyID,PreAdjustPrice,OriginalPolicyType,CostRate,PackageOption,IsBooking,TransitType
   * </pre>
   *
   * <code>repeated .com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType DeprecatedTag = 2;</code>
   */
  int getDeprecatedTagCount();
  /**
   * <pre>
   **
   *对应原DeprecatedInfo 作为待废弃兼容实体的替换
   *Key：ProductType,PolicyID,PolicyCategory,PolicyType,LateCostPrice,ShareNormalPolicyID,PreAdjustPrice,OriginalPolicyType,CostRate,PackageOption,IsBooking,TransitType
   * </pre>
   *
   * <code>repeated .com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType DeprecatedTag = 2;</code>
   */
  java.util.List<? extends com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairTypeOrBuilder> 
      getDeprecatedTagOrBuilderList();
  /**
   * <pre>
   **
   *对应原DeprecatedInfo 作为待废弃兼容实体的替换
   *Key：ProductType,PolicyID,PolicyCategory,PolicyType,LateCostPrice,ShareNormalPolicyID,PreAdjustPrice,OriginalPolicyType,CostRate,PackageOption,IsBooking,TransitType
   * </pre>
   *
   * <code>repeated .com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType DeprecatedTag = 2;</code>
   */
  com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairTypeOrBuilder getDeprecatedTagOrBuilder(
      int index);

  /**
   * <pre>
   **
   *对应原DeprecatedInfo.AdditionalInfoList
   *2	 :NE_3U_DIRECT_REDUCTION, 川航东北区直减， value为对应的营销代码(MarketingCode, string)
   *3	 :废弃,保留占位
   *4	 :WaitingApplyPolicy_SuccessRate, 抢票成功率，value格式为"AVG|0.00,24H|0.00,72H|0.00,PQ_AVG|0.00,PQ_24H|0.00,PQ_72H|0.00,"
   *5	 :FLOAT_UP_GEAR, 航司上浮ABTest, value为档位ID，自动生成，仅用于分组(int)
   *6	 :Policy_UpgradeRule, 政策升舱规则,value为OutputUpgradeInfoEntity的Newtonsoft json序列化
   *7	 :废弃,保留占位 -- LuggageRemarks
   *8	 :MembershipRegisterType, 会员注册方式，value为 1：联系人注册，2：单个乘机人注册，3：多个乘机人注册
   *9	 :废弃,保留占位
   *10	 :废弃,保留占位 -- LuggageShowType, 行李额展示方式，value为 1：展示合计行李额
   *11	 :PriceAdjustment, 废弃
   *12	 :RebateInfo, 返现信息， value格式为类型+冒号+金额，当前类型仅为RebateAmount， 示例为 RebateAmount:20
   *13	 :废弃,保留占位
   *14	 :废弃,保留占位
   * </pre>
   *
   * <code>repeated .com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType AdditionalTag = 3;</code>
   */
  java.util.List<com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType> 
      getAdditionalTagList();
  /**
   * <pre>
   **
   *对应原DeprecatedInfo.AdditionalInfoList
   *2	 :NE_3U_DIRECT_REDUCTION, 川航东北区直减， value为对应的营销代码(MarketingCode, string)
   *3	 :废弃,保留占位
   *4	 :WaitingApplyPolicy_SuccessRate, 抢票成功率，value格式为"AVG|0.00,24H|0.00,72H|0.00,PQ_AVG|0.00,PQ_24H|0.00,PQ_72H|0.00,"
   *5	 :FLOAT_UP_GEAR, 航司上浮ABTest, value为档位ID，自动生成，仅用于分组(int)
   *6	 :Policy_UpgradeRule, 政策升舱规则,value为OutputUpgradeInfoEntity的Newtonsoft json序列化
   *7	 :废弃,保留占位 -- LuggageRemarks
   *8	 :MembershipRegisterType, 会员注册方式，value为 1：联系人注册，2：单个乘机人注册，3：多个乘机人注册
   *9	 :废弃,保留占位
   *10	 :废弃,保留占位 -- LuggageShowType, 行李额展示方式，value为 1：展示合计行李额
   *11	 :PriceAdjustment, 废弃
   *12	 :RebateInfo, 返现信息， value格式为类型+冒号+金额，当前类型仅为RebateAmount， 示例为 RebateAmount:20
   *13	 :废弃,保留占位
   *14	 :废弃,保留占位
   * </pre>
   *
   * <code>repeated .com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType AdditionalTag = 3;</code>
   */
  com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType getAdditionalTag(int index);
  /**
   * <pre>
   **
   *对应原DeprecatedInfo.AdditionalInfoList
   *2	 :NE_3U_DIRECT_REDUCTION, 川航东北区直减， value为对应的营销代码(MarketingCode, string)
   *3	 :废弃,保留占位
   *4	 :WaitingApplyPolicy_SuccessRate, 抢票成功率，value格式为"AVG|0.00,24H|0.00,72H|0.00,PQ_AVG|0.00,PQ_24H|0.00,PQ_72H|0.00,"
   *5	 :FLOAT_UP_GEAR, 航司上浮ABTest, value为档位ID，自动生成，仅用于分组(int)
   *6	 :Policy_UpgradeRule, 政策升舱规则,value为OutputUpgradeInfoEntity的Newtonsoft json序列化
   *7	 :废弃,保留占位 -- LuggageRemarks
   *8	 :MembershipRegisterType, 会员注册方式，value为 1：联系人注册，2：单个乘机人注册，3：多个乘机人注册
   *9	 :废弃,保留占位
   *10	 :废弃,保留占位 -- LuggageShowType, 行李额展示方式，value为 1：展示合计行李额
   *11	 :PriceAdjustment, 废弃
   *12	 :RebateInfo, 返现信息， value格式为类型+冒号+金额，当前类型仅为RebateAmount， 示例为 RebateAmount:20
   *13	 :废弃,保留占位
   *14	 :废弃,保留占位
   * </pre>
   *
   * <code>repeated .com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType AdditionalTag = 3;</code>
   */
  int getAdditionalTagCount();
  /**
   * <pre>
   **
   *对应原DeprecatedInfo.AdditionalInfoList
   *2	 :NE_3U_DIRECT_REDUCTION, 川航东北区直减， value为对应的营销代码(MarketingCode, string)
   *3	 :废弃,保留占位
   *4	 :WaitingApplyPolicy_SuccessRate, 抢票成功率，value格式为"AVG|0.00,24H|0.00,72H|0.00,PQ_AVG|0.00,PQ_24H|0.00,PQ_72H|0.00,"
   *5	 :FLOAT_UP_GEAR, 航司上浮ABTest, value为档位ID，自动生成，仅用于分组(int)
   *6	 :Policy_UpgradeRule, 政策升舱规则,value为OutputUpgradeInfoEntity的Newtonsoft json序列化
   *7	 :废弃,保留占位 -- LuggageRemarks
   *8	 :MembershipRegisterType, 会员注册方式，value为 1：联系人注册，2：单个乘机人注册，3：多个乘机人注册
   *9	 :废弃,保留占位
   *10	 :废弃,保留占位 -- LuggageShowType, 行李额展示方式，value为 1：展示合计行李额
   *11	 :PriceAdjustment, 废弃
   *12	 :RebateInfo, 返现信息， value格式为类型+冒号+金额，当前类型仅为RebateAmount， 示例为 RebateAmount:20
   *13	 :废弃,保留占位
   *14	 :废弃,保留占位
   * </pre>
   *
   * <code>repeated .com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType AdditionalTag = 3;</code>
   */
  java.util.List<? extends com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairTypeOrBuilder> 
      getAdditionalTagOrBuilderList();
  /**
   * <pre>
   **
   *对应原DeprecatedInfo.AdditionalInfoList
   *2	 :NE_3U_DIRECT_REDUCTION, 川航东北区直减， value为对应的营销代码(MarketingCode, string)
   *3	 :废弃,保留占位
   *4	 :WaitingApplyPolicy_SuccessRate, 抢票成功率，value格式为"AVG|0.00,24H|0.00,72H|0.00,PQ_AVG|0.00,PQ_24H|0.00,PQ_72H|0.00,"
   *5	 :FLOAT_UP_GEAR, 航司上浮ABTest, value为档位ID，自动生成，仅用于分组(int)
   *6	 :Policy_UpgradeRule, 政策升舱规则,value为OutputUpgradeInfoEntity的Newtonsoft json序列化
   *7	 :废弃,保留占位 -- LuggageRemarks
   *8	 :MembershipRegisterType, 会员注册方式，value为 1：联系人注册，2：单个乘机人注册，3：多个乘机人注册
   *9	 :废弃,保留占位
   *10	 :废弃,保留占位 -- LuggageShowType, 行李额展示方式，value为 1：展示合计行李额
   *11	 :PriceAdjustment, 废弃
   *12	 :RebateInfo, 返现信息， value格式为类型+冒号+金额，当前类型仅为RebateAmount， 示例为 RebateAmount:20
   *13	 :废弃,保留占位
   *14	 :废弃,保留占位
   * </pre>
   *
   * <code>repeated .com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType AdditionalTag = 3;</code>
   */
  com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairTypeOrBuilder getAdditionalTagOrBuilder(
      int index);

  /**
   * <pre>
   * 分票信息
   * </pre>
   *
   * <code>.com.ctrip.flight.agg.shopping.contract.transportation.response.TicketSharingType TicketSharing = 4;</code>
   */
  boolean hasTicketSharing();
  /**
   * <pre>
   * 分票信息
   * </pre>
   *
   * <code>.com.ctrip.flight.agg.shopping.contract.transportation.response.TicketSharingType TicketSharing = 4;</code>
   */
  com.ctrip.flight.agg.shopping.contract.transportation.response.TicketSharingType getTicketSharing();
  /**
   * <pre>
   * 分票信息
   * </pre>
   *
   * <code>.com.ctrip.flight.agg.shopping.contract.transportation.response.TicketSharingType TicketSharing = 4;</code>
   */
  com.ctrip.flight.agg.shopping.contract.transportation.response.TicketSharingTypeOrBuilder getTicketSharingOrBuilder();

  /**
   * <pre>
   * 中转政策信息
   * </pre>
   *
   * <code>.com.ctrip.flight.agg.shopping.contract.transportation.response.TransitPolicyType TransitPolicy = 5;</code>
   */
  boolean hasTransitPolicy();
  /**
   * <pre>
   * 中转政策信息
   * </pre>
   *
   * <code>.com.ctrip.flight.agg.shopping.contract.transportation.response.TransitPolicyType TransitPolicy = 5;</code>
   */
  com.ctrip.flight.agg.shopping.contract.transportation.response.TransitPolicyType getTransitPolicy();
  /**
   * <pre>
   * 中转政策信息
   * </pre>
   *
   * <code>.com.ctrip.flight.agg.shopping.contract.transportation.response.TransitPolicyType TransitPolicy = 5;</code>
   */
  com.ctrip.flight.agg.shopping.contract.transportation.response.TransitPolicyTypeOrBuilder getTransitPolicyOrBuilder();
}
