// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com.ctrip.flight.agg.shopping.contract.transportation.response.proto

package com.ctrip.flight.agg.shopping.contract.transportation.response;

public interface PremiumProductTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ctrip.flight.agg.shopping.contract.transportation.response.PremiumProductType)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 搭赠类型
   * </pre>
   *
   * <code>int32 BundleSaleType = 1;</code>
   */
  int getBundleSaleType();
}
