// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com.ctrip.flight.agg.shopping.contract.transportation.response.proto

package com.ctrip.flight.agg.shopping.contract.transportation.response;

public interface TrainProductTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ctrip.flight.agg.shopping.contract.transportation.response.TrainProductType)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 索引号
   * </pre>
   *
   * <code>int32 RefNum = 1;</code>
   */
  int getRefNum();

  /**
   * <pre>
   * 根据乘客类型和乘客资质划分的火车价格信息
   * </pre>
   *
   * <code>repeated .com.ctrip.flight.agg.shopping.contract.transportation.PaxProductType PaxProduct = 2;</code>
   */
  java.util.List<com.ctrip.flight.agg.shopping.contract.transportation.PaxProductType> 
      getPaxProductList();
  /**
   * <pre>
   * 根据乘客类型和乘客资质划分的火车价格信息
   * </pre>
   *
   * <code>repeated .com.ctrip.flight.agg.shopping.contract.transportation.PaxProductType PaxProduct = 2;</code>
   */
  com.ctrip.flight.agg.shopping.contract.transportation.PaxProductType getPaxProduct(int index);
  /**
   * <pre>
   * 根据乘客类型和乘客资质划分的火车价格信息
   * </pre>
   *
   * <code>repeated .com.ctrip.flight.agg.shopping.contract.transportation.PaxProductType PaxProduct = 2;</code>
   */
  int getPaxProductCount();
  /**
   * <pre>
   * 根据乘客类型和乘客资质划分的火车价格信息
   * </pre>
   *
   * <code>repeated .com.ctrip.flight.agg.shopping.contract.transportation.PaxProductType PaxProduct = 2;</code>
   */
  java.util.List<? extends com.ctrip.flight.agg.shopping.contract.transportation.PaxProductTypeOrBuilder> 
      getPaxProductOrBuilderList();
  /**
   * <pre>
   * 根据乘客类型和乘客资质划分的火车价格信息
   * </pre>
   *
   * <code>repeated .com.ctrip.flight.agg.shopping.contract.transportation.PaxProductType PaxProduct = 2;</code>
   */
  com.ctrip.flight.agg.shopping.contract.transportation.PaxProductTypeOrBuilder getPaxProductOrBuilder(
      int index);

  /**
   * <pre>
   * 促销标签
   * </pre>
   *
   * <code>string PromotionTag = 3;</code>
   */
  java.lang.String getPromotionTag();
  /**
   * <pre>
   * 促销标签
   * </pre>
   *
   * <code>string PromotionTag = 3;</code>
   */
  com.google.protobuf.ByteString
      getPromotionTagBytes();

  /**
   * <pre>
   * 详情查询时存放token等扩展信息
   * </pre>
   *
   * <code>repeated .com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType Tag = 4;</code>
   */
  java.util.List<com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType> 
      getTagList();
  /**
   * <pre>
   * 详情查询时存放token等扩展信息
   * </pre>
   *
   * <code>repeated .com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType Tag = 4;</code>
   */
  com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType getTag(int index);
  /**
   * <pre>
   * 详情查询时存放token等扩展信息
   * </pre>
   *
   * <code>repeated .com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType Tag = 4;</code>
   */
  int getTagCount();
  /**
   * <pre>
   * 详情查询时存放token等扩展信息
   * </pre>
   *
   * <code>repeated .com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType Tag = 4;</code>
   */
  java.util.List<? extends com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairTypeOrBuilder> 
      getTagOrBuilderList();
  /**
   * <pre>
   * 详情查询时存放token等扩展信息
   * </pre>
   *
   * <code>repeated .com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType Tag = 4;</code>
   */
  com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairTypeOrBuilder getTagOrBuilder(
      int index);

  /**
   * <pre>
   * 退改签简体信息
   * </pre>
   *
   * <code>.com.ctrip.flight.agg.shopping.contract.transportation.RefundChangeType RefundChange = 5;</code>
   */
  boolean hasRefundChange();
  /**
   * <pre>
   * 退改签简体信息
   * </pre>
   *
   * <code>.com.ctrip.flight.agg.shopping.contract.transportation.RefundChangeType RefundChange = 5;</code>
   */
  com.ctrip.flight.agg.shopping.contract.transportation.RefundChangeType getRefundChange();
  /**
   * <pre>
   * 退改签简体信息
   * </pre>
   *
   * <code>.com.ctrip.flight.agg.shopping.contract.transportation.RefundChangeType RefundChange = 5;</code>
   */
  com.ctrip.flight.agg.shopping.contract.transportation.RefundChangeTypeOrBuilder getRefundChangeOrBuilder();

  /**
   * <pre>
   * 火车票token
   * </pre>
   *
   * <code>string TrainToken = 6;</code>
   */
  java.lang.String getTrainToken();
  /**
   * <pre>
   * 火车票token
   * </pre>
   *
   * <code>string TrainToken = 6;</code>
   */
  com.google.protobuf.ByteString
      getTrainTokenBytes();

  /**
   * <pre>
   * X铁组合规则ID
   * </pre>
   *
   * <code>int64 RuleID = 7;</code>
   */
  long getRuleID();
}
