// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com.ctrip.flight.agg.shopping.contract.transportation.request.proto

package com.ctrip.flight.agg.shopping.contract.transportation.request;

/**
 * Protobuf type {@code com.ctrip.flight.agg.shopping.contract.transportation.request.FlightSpecifiedOptionType}
 */
public  final class FlightSpecifiedOptionType extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.ctrip.flight.agg.shopping.contract.transportation.request.FlightSpecifiedOptionType)
    FlightSpecifiedOptionTypeOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FlightSpecifiedOptionType.newBuilder() to construct.
  private FlightSpecifiedOptionType(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FlightSpecifiedOptionType() {
    operatingCarrier_ = "";
    cabinCode_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    rBD_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FlightSpecifiedOptionType(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            operatingCarrier_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              cabinCode_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000002;
            }
            cabinCode_.add(s);
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            rBD_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        cabinCode_ = cabinCode_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ctrip.flight.agg.shopping.contract.transportation.request.ComCtripFlightAggShoppingContractTransportationRequest.internal_static_com_ctrip_flight_agg_shopping_contract_transportation_request_FlightSpecifiedOptionType_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ctrip.flight.agg.shopping.contract.transportation.request.ComCtripFlightAggShoppingContractTransportationRequest.internal_static_com_ctrip_flight_agg_shopping_contract_transportation_request_FlightSpecifiedOptionType_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ctrip.flight.agg.shopping.contract.transportation.request.FlightSpecifiedOptionType.class, com.ctrip.flight.agg.shopping.contract.transportation.request.FlightSpecifiedOptionType.Builder.class);
  }

  private int bitField0_;
  public static final int OPERATINGCARRIER_FIELD_NUMBER = 1;
  private volatile java.lang.Object operatingCarrier_;
  /**
   * <pre>
   * 实际承运航司
   * </pre>
   *
   * <code>string OperatingCarrier = 1;</code>
   */
  public java.lang.String getOperatingCarrier() {
    java.lang.Object ref = operatingCarrier_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      operatingCarrier_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 实际承运航司
   * </pre>
   *
   * <code>string OperatingCarrier = 1;</code>
   */
  public com.google.protobuf.ByteString
      getOperatingCarrierBytes() {
    java.lang.Object ref = operatingCarrier_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      operatingCarrier_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CABINCODE_FIELD_NUMBER = 5;
  private com.google.protobuf.LazyStringList cabinCode_;
  /**
   * <pre>
   * 舱等。支持 Y W C F四种舱等
   * </pre>
   *
   * <code>repeated string CabinCode = 5;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getCabinCodeList() {
    return cabinCode_;
  }
  /**
   * <pre>
   * 舱等。支持 Y W C F四种舱等
   * </pre>
   *
   * <code>repeated string CabinCode = 5;</code>
   */
  public int getCabinCodeCount() {
    return cabinCode_.size();
  }
  /**
   * <pre>
   * 舱等。支持 Y W C F四种舱等
   * </pre>
   *
   * <code>repeated string CabinCode = 5;</code>
   */
  public java.lang.String getCabinCode(int index) {
    return cabinCode_.get(index);
  }
  /**
   * <pre>
   * 舱等。支持 Y W C F四种舱等
   * </pre>
   *
   * <code>repeated string CabinCode = 5;</code>
   */
  public com.google.protobuf.ByteString
      getCabinCodeBytes(int index) {
    return cabinCode_.getByteString(index);
  }

  public static final int RBD_FIELD_NUMBER = 6;
  private volatile java.lang.Object rBD_;
  /**
   * <pre>
   * 子仓
   * </pre>
   *
   * <code>string RBD = 6;</code>
   */
  public java.lang.String getRBD() {
    java.lang.Object ref = rBD_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      rBD_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 子仓
   * </pre>
   *
   * <code>string RBD = 6;</code>
   */
  public com.google.protobuf.ByteString
      getRBDBytes() {
    java.lang.Object ref = rBD_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      rBD_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getOperatingCarrierBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, operatingCarrier_);
    }
    for (int i = 0; i < cabinCode_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, cabinCode_.getRaw(i));
    }
    if (!getRBDBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, rBD_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getOperatingCarrierBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, operatingCarrier_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < cabinCode_.size(); i++) {
        dataSize += computeStringSizeNoTag(cabinCode_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getCabinCodeList().size();
    }
    if (!getRBDBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, rBD_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ctrip.flight.agg.shopping.contract.transportation.request.FlightSpecifiedOptionType)) {
      return super.equals(obj);
    }
    com.ctrip.flight.agg.shopping.contract.transportation.request.FlightSpecifiedOptionType other = (com.ctrip.flight.agg.shopping.contract.transportation.request.FlightSpecifiedOptionType) obj;

    boolean result = true;
    result = result && getOperatingCarrier()
        .equals(other.getOperatingCarrier());
    result = result && getCabinCodeList()
        .equals(other.getCabinCodeList());
    result = result && getRBD()
        .equals(other.getRBD());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + OPERATINGCARRIER_FIELD_NUMBER;
    hash = (53 * hash) + getOperatingCarrier().hashCode();
    if (getCabinCodeCount() > 0) {
      hash = (37 * hash) + CABINCODE_FIELD_NUMBER;
      hash = (53 * hash) + getCabinCodeList().hashCode();
    }
    hash = (37 * hash) + RBD_FIELD_NUMBER;
    hash = (53 * hash) + getRBD().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ctrip.flight.agg.shopping.contract.transportation.request.FlightSpecifiedOptionType parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ctrip.flight.agg.shopping.contract.transportation.request.FlightSpecifiedOptionType parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ctrip.flight.agg.shopping.contract.transportation.request.FlightSpecifiedOptionType parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ctrip.flight.agg.shopping.contract.transportation.request.FlightSpecifiedOptionType parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ctrip.flight.agg.shopping.contract.transportation.request.FlightSpecifiedOptionType parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ctrip.flight.agg.shopping.contract.transportation.request.FlightSpecifiedOptionType parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ctrip.flight.agg.shopping.contract.transportation.request.FlightSpecifiedOptionType parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ctrip.flight.agg.shopping.contract.transportation.request.FlightSpecifiedOptionType parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ctrip.flight.agg.shopping.contract.transportation.request.FlightSpecifiedOptionType parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ctrip.flight.agg.shopping.contract.transportation.request.FlightSpecifiedOptionType parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ctrip.flight.agg.shopping.contract.transportation.request.FlightSpecifiedOptionType parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ctrip.flight.agg.shopping.contract.transportation.request.FlightSpecifiedOptionType parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ctrip.flight.agg.shopping.contract.transportation.request.FlightSpecifiedOptionType prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.ctrip.flight.agg.shopping.contract.transportation.request.FlightSpecifiedOptionType}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.ctrip.flight.agg.shopping.contract.transportation.request.FlightSpecifiedOptionType)
      com.ctrip.flight.agg.shopping.contract.transportation.request.FlightSpecifiedOptionTypeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ctrip.flight.agg.shopping.contract.transportation.request.ComCtripFlightAggShoppingContractTransportationRequest.internal_static_com_ctrip_flight_agg_shopping_contract_transportation_request_FlightSpecifiedOptionType_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ctrip.flight.agg.shopping.contract.transportation.request.ComCtripFlightAggShoppingContractTransportationRequest.internal_static_com_ctrip_flight_agg_shopping_contract_transportation_request_FlightSpecifiedOptionType_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ctrip.flight.agg.shopping.contract.transportation.request.FlightSpecifiedOptionType.class, com.ctrip.flight.agg.shopping.contract.transportation.request.FlightSpecifiedOptionType.Builder.class);
    }

    // Construct using com.ctrip.flight.agg.shopping.contract.transportation.request.FlightSpecifiedOptionType.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      operatingCarrier_ = "";

      cabinCode_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      rBD_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ctrip.flight.agg.shopping.contract.transportation.request.ComCtripFlightAggShoppingContractTransportationRequest.internal_static_com_ctrip_flight_agg_shopping_contract_transportation_request_FlightSpecifiedOptionType_descriptor;
    }

    @java.lang.Override
    public com.ctrip.flight.agg.shopping.contract.transportation.request.FlightSpecifiedOptionType getDefaultInstanceForType() {
      return com.ctrip.flight.agg.shopping.contract.transportation.request.FlightSpecifiedOptionType.getDefaultInstance();
    }

    @java.lang.Override
    public com.ctrip.flight.agg.shopping.contract.transportation.request.FlightSpecifiedOptionType build() {
      com.ctrip.flight.agg.shopping.contract.transportation.request.FlightSpecifiedOptionType result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ctrip.flight.agg.shopping.contract.transportation.request.FlightSpecifiedOptionType buildPartial() {
      com.ctrip.flight.agg.shopping.contract.transportation.request.FlightSpecifiedOptionType result = new com.ctrip.flight.agg.shopping.contract.transportation.request.FlightSpecifiedOptionType(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.operatingCarrier_ = operatingCarrier_;
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        cabinCode_ = cabinCode_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.cabinCode_ = cabinCode_;
      result.rBD_ = rBD_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ctrip.flight.agg.shopping.contract.transportation.request.FlightSpecifiedOptionType) {
        return mergeFrom((com.ctrip.flight.agg.shopping.contract.transportation.request.FlightSpecifiedOptionType)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ctrip.flight.agg.shopping.contract.transportation.request.FlightSpecifiedOptionType other) {
      if (other == com.ctrip.flight.agg.shopping.contract.transportation.request.FlightSpecifiedOptionType.getDefaultInstance()) return this;
      if (!other.getOperatingCarrier().isEmpty()) {
        operatingCarrier_ = other.operatingCarrier_;
        onChanged();
      }
      if (!other.cabinCode_.isEmpty()) {
        if (cabinCode_.isEmpty()) {
          cabinCode_ = other.cabinCode_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureCabinCodeIsMutable();
          cabinCode_.addAll(other.cabinCode_);
        }
        onChanged();
      }
      if (!other.getRBD().isEmpty()) {
        rBD_ = other.rBD_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ctrip.flight.agg.shopping.contract.transportation.request.FlightSpecifiedOptionType parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ctrip.flight.agg.shopping.contract.transportation.request.FlightSpecifiedOptionType) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object operatingCarrier_ = "";
    /**
     * <pre>
     * 实际承运航司
     * </pre>
     *
     * <code>string OperatingCarrier = 1;</code>
     */
    public java.lang.String getOperatingCarrier() {
      java.lang.Object ref = operatingCarrier_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        operatingCarrier_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 实际承运航司
     * </pre>
     *
     * <code>string OperatingCarrier = 1;</code>
     */
    public com.google.protobuf.ByteString
        getOperatingCarrierBytes() {
      java.lang.Object ref = operatingCarrier_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        operatingCarrier_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 实际承运航司
     * </pre>
     *
     * <code>string OperatingCarrier = 1;</code>
     */
    public Builder setOperatingCarrier(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      operatingCarrier_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 实际承运航司
     * </pre>
     *
     * <code>string OperatingCarrier = 1;</code>
     */
    public Builder clearOperatingCarrier() {
      
      operatingCarrier_ = getDefaultInstance().getOperatingCarrier();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 实际承运航司
     * </pre>
     *
     * <code>string OperatingCarrier = 1;</code>
     */
    public Builder setOperatingCarrierBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      operatingCarrier_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList cabinCode_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureCabinCodeIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        cabinCode_ = new com.google.protobuf.LazyStringArrayList(cabinCode_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <pre>
     * 舱等。支持 Y W C F四种舱等
     * </pre>
     *
     * <code>repeated string CabinCode = 5;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getCabinCodeList() {
      return cabinCode_.getUnmodifiableView();
    }
    /**
     * <pre>
     * 舱等。支持 Y W C F四种舱等
     * </pre>
     *
     * <code>repeated string CabinCode = 5;</code>
     */
    public int getCabinCodeCount() {
      return cabinCode_.size();
    }
    /**
     * <pre>
     * 舱等。支持 Y W C F四种舱等
     * </pre>
     *
     * <code>repeated string CabinCode = 5;</code>
     */
    public java.lang.String getCabinCode(int index) {
      return cabinCode_.get(index);
    }
    /**
     * <pre>
     * 舱等。支持 Y W C F四种舱等
     * </pre>
     *
     * <code>repeated string CabinCode = 5;</code>
     */
    public com.google.protobuf.ByteString
        getCabinCodeBytes(int index) {
      return cabinCode_.getByteString(index);
    }
    /**
     * <pre>
     * 舱等。支持 Y W C F四种舱等
     * </pre>
     *
     * <code>repeated string CabinCode = 5;</code>
     */
    public Builder setCabinCode(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureCabinCodeIsMutable();
      cabinCode_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 舱等。支持 Y W C F四种舱等
     * </pre>
     *
     * <code>repeated string CabinCode = 5;</code>
     */
    public Builder addCabinCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureCabinCodeIsMutable();
      cabinCode_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 舱等。支持 Y W C F四种舱等
     * </pre>
     *
     * <code>repeated string CabinCode = 5;</code>
     */
    public Builder addAllCabinCode(
        java.lang.Iterable<java.lang.String> values) {
      ensureCabinCodeIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, cabinCode_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 舱等。支持 Y W C F四种舱等
     * </pre>
     *
     * <code>repeated string CabinCode = 5;</code>
     */
    public Builder clearCabinCode() {
      cabinCode_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 舱等。支持 Y W C F四种舱等
     * </pre>
     *
     * <code>repeated string CabinCode = 5;</code>
     */
    public Builder addCabinCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureCabinCodeIsMutable();
      cabinCode_.add(value);
      onChanged();
      return this;
    }

    private java.lang.Object rBD_ = "";
    /**
     * <pre>
     * 子仓
     * </pre>
     *
     * <code>string RBD = 6;</code>
     */
    public java.lang.String getRBD() {
      java.lang.Object ref = rBD_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        rBD_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 子仓
     * </pre>
     *
     * <code>string RBD = 6;</code>
     */
    public com.google.protobuf.ByteString
        getRBDBytes() {
      java.lang.Object ref = rBD_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rBD_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 子仓
     * </pre>
     *
     * <code>string RBD = 6;</code>
     */
    public Builder setRBD(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      rBD_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 子仓
     * </pre>
     *
     * <code>string RBD = 6;</code>
     */
    public Builder clearRBD() {
      
      rBD_ = getDefaultInstance().getRBD();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 子仓
     * </pre>
     *
     * <code>string RBD = 6;</code>
     */
    public Builder setRBDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      rBD_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.ctrip.flight.agg.shopping.contract.transportation.request.FlightSpecifiedOptionType)
  }

  // @@protoc_insertion_point(class_scope:com.ctrip.flight.agg.shopping.contract.transportation.request.FlightSpecifiedOptionType)
  private static final com.ctrip.flight.agg.shopping.contract.transportation.request.FlightSpecifiedOptionType DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ctrip.flight.agg.shopping.contract.transportation.request.FlightSpecifiedOptionType();
  }

  public static com.ctrip.flight.agg.shopping.contract.transportation.request.FlightSpecifiedOptionType getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FlightSpecifiedOptionType>
      PARSER = new com.google.protobuf.AbstractParser<FlightSpecifiedOptionType>() {
    @java.lang.Override
    public FlightSpecifiedOptionType parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FlightSpecifiedOptionType(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FlightSpecifiedOptionType> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FlightSpecifiedOptionType> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ctrip.flight.agg.shopping.contract.transportation.request.FlightSpecifiedOptionType getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

