// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com.ctrip.flight.agg.shopping.contract.transportation.request.proto

package com.ctrip.flight.agg.shopping.contract.transportation.request;

public interface PaxDetailTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ctrip.flight.agg.shopping.contract.transportation.request.PaxDetailType)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 年龄
   * </pre>
   *
   * <code>int32 Age = 1;</code>
   */
  int getAge();

  /**
   * <pre>
   * 性别
   * </pre>
   *
   * <code>string Sex = 2;</code>
   */
  java.lang.String getSex();
  /**
   * <pre>
   * 性别
   * </pre>
   *
   * <code>string Sex = 2;</code>
   */
  com.google.protobuf.ByteString
      getSexBytes();

  /**
   * <pre>
   * 证件类型
   * </pre>
   *
   * <code>string IdentityType = 3;</code>
   */
  java.lang.String getIdentityType();
  /**
   * <pre>
   * 证件类型
   * </pre>
   *
   * <code>string IdentityType = 3;</code>
   */
  com.google.protobuf.ByteString
      getIdentityTypeBytes();

  /**
   * <pre>
   * 证件号码
   * </pre>
   *
   * <code>string IdentityNumber = 4;</code>
   */
  java.lang.String getIdentityNumber();
  /**
   * <pre>
   * 证件号码
   * </pre>
   *
   * <code>string IdentityNumber = 4;</code>
   */
  com.google.protobuf.ByteString
      getIdentityNumberBytes();
}
