// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com.ctrip.flight.agg.shopping.contract.transportation.proto

package com.ctrip.flight.agg.shopping.contract.transportation;

public interface AdvertDetailTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ctrip.flight.agg.shopping.contract.transportation.AdvertDetailType)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 产品类型，GiftProduct：礼盒，CouponProduct：优惠券，InsuranceProduct：保险，FlightXComposition：三选X、赠定减、X打包，VIPLounge：休息室，SecurityChannel：安检通道，Parking：停车场，ComboXRule：买X赠X，AdvertXPackage：广告营销N选X，MemberInterest：会员权益（旅行家），Specialty：实物，PickUp：接送机。WIFI：WIFI，FlightCoupon：机票券，PickUpCoupon：接送机券
   * </pre>
   *
   * <code>string ProductType = 1;</code>
   */
  java.lang.String getProductType();
  /**
   * <pre>
   * 产品类型，GiftProduct：礼盒，CouponProduct：优惠券，InsuranceProduct：保险，FlightXComposition：三选X、赠定减、X打包，VIPLounge：休息室，SecurityChannel：安检通道，Parking：停车场，ComboXRule：买X赠X，AdvertXPackage：广告营销N选X，MemberInterest：会员权益（旅行家），Specialty：实物，PickUp：接送机。WIFI：WIFI，FlightCoupon：机票券，PickUpCoupon：接送机券
   * </pre>
   *
   * <code>string ProductType = 1;</code>
   */
  com.google.protobuf.ByteString
      getProductTypeBytes();

  /**
   * <pre>
   * 子产品类型
   * </pre>
   *
   * <code>string SubProductType = 2;</code>
   */
  java.lang.String getSubProductType();
  /**
   * <pre>
   * 子产品类型
   * </pre>
   *
   * <code>string SubProductType = 2;</code>
   */
  com.google.protobuf.ByteString
      getSubProductTypeBytes();

  /**
   * <pre>
   * 产品ID
   * </pre>
   *
   * <code>string ProductID = 3;</code>
   */
  java.lang.String getProductID();
  /**
   * <pre>
   * 产品ID
   * </pre>
   *
   * <code>string ProductID = 3;</code>
   */
  com.google.protobuf.ByteString
      getProductIDBytes();

  /**
   * <pre>
   * 售价
   * </pre>
   *
   * <code>double SalePrice = 4;</code>
   */
  double getSalePrice();

  /**
   * <pre>
   * 面价
   * </pre>
   *
   * <code>double PublishPrice = 5;</code>
   */
  double getPublishPrice();
}
