// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com.ctrip.flight.agg.shopping.contract.transportation.proto

package com.ctrip.flight.agg.shopping.contract.transportation;

public interface AdvertTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ctrip.flight.agg.shopping.contract.transportation.AdvertType)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 索引id
   * </pre>
   *
   * <code>int32 RefNum = 1;</code>
   */
  int getRefNum();

  /**
   * <pre>
   * 广告x产品详情
   * </pre>
   *
   * <code>repeated .com.ctrip.flight.agg.shopping.contract.transportation.AdvertDetailType AdvertDetail = 2;</code>
   */
  java.util.List<com.ctrip.flight.agg.shopping.contract.transportation.AdvertDetailType> 
      getAdvertDetailList();
  /**
   * <pre>
   * 广告x产品详情
   * </pre>
   *
   * <code>repeated .com.ctrip.flight.agg.shopping.contract.transportation.AdvertDetailType AdvertDetail = 2;</code>
   */
  com.ctrip.flight.agg.shopping.contract.transportation.AdvertDetailType getAdvertDetail(int index);
  /**
   * <pre>
   * 广告x产品详情
   * </pre>
   *
   * <code>repeated .com.ctrip.flight.agg.shopping.contract.transportation.AdvertDetailType AdvertDetail = 2;</code>
   */
  int getAdvertDetailCount();
  /**
   * <pre>
   * 广告x产品详情
   * </pre>
   *
   * <code>repeated .com.ctrip.flight.agg.shopping.contract.transportation.AdvertDetailType AdvertDetail = 2;</code>
   */
  java.util.List<? extends com.ctrip.flight.agg.shopping.contract.transportation.AdvertDetailTypeOrBuilder> 
      getAdvertDetailOrBuilderList();
  /**
   * <pre>
   * 广告x产品详情
   * </pre>
   *
   * <code>repeated .com.ctrip.flight.agg.shopping.contract.transportation.AdvertDetailType AdvertDetail = 2;</code>
   */
  com.ctrip.flight.agg.shopping.contract.transportation.AdvertDetailTypeOrBuilder getAdvertDetailOrBuilder(
      int index);
}
