// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com.ctrip.flight.agg.shopping.contract.transportation.proto

package com.ctrip.flight.agg.shopping.contract.transportation;

public interface CacheTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ctrip.flight.agg.shopping.contract.transportation.CacheType)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 RefNum = 1;</code>
   */
  int getRefNum();

  /**
   * <code>int32 AgeInMillisecond = 2;</code>
   */
  int getAgeInMillisecond();

  /**
   * <code>string TraceID = 3;</code>
   */
  java.lang.String getTraceID();
  /**
   * <code>string TraceID = 3;</code>
   */
  com.google.protobuf.ByteString
      getTraceIDBytes();
}
