// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com.ctrip.flight.agg.shopping.contract.transportation.proto

package com.ctrip.flight.agg.shopping.contract.transportation;

/**
 * Protobuf type {@code com.ctrip.flight.agg.shopping.contract.transportation.PaxProductType}
 */
public  final class PaxProductType extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.ctrip.flight.agg.shopping.contract.transportation.PaxProductType)
    PaxProductTypeOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PaxProductType.newBuilder() to construct.
  private PaxProductType(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PaxProductType() {
    ageType_ = 0;
    tag_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PaxProductType(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            ageType_ = input.readInt32();
            break;
          }
          case 18: {
            com.ctrip.flight.agg.shopping.contract.transportation.SaleCurrencyPriceDetailType.Builder subBuilder = null;
            if (saleCurrencyPriceDetail_ != null) {
              subBuilder = saleCurrencyPriceDetail_.toBuilder();
            }
            saleCurrencyPriceDetail_ = input.readMessage(com.ctrip.flight.agg.shopping.contract.transportation.SaleCurrencyPriceDetailType.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(saleCurrencyPriceDetail_);
              saleCurrencyPriceDetail_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            com.ctrip.flight.agg.shopping.contract.transportation.SettlementCurrencyPriceDetailType.Builder subBuilder = null;
            if (settlementCurrencyPriceDetail_ != null) {
              subBuilder = settlementCurrencyPriceDetail_.toBuilder();
            }
            settlementCurrencyPriceDetail_ = input.readMessage(com.ctrip.flight.agg.shopping.contract.transportation.SettlementCurrencyPriceDetailType.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(settlementCurrencyPriceDetail_);
              settlementCurrencyPriceDetail_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
              tag_ = new java.util.ArrayList<com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType>();
              mutable_bitField0_ |= 0x00000008;
            }
            tag_.add(
                input.readMessage(com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
        tag_ = java.util.Collections.unmodifiableList(tag_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ctrip.flight.agg.shopping.contract.transportation.ComCtripFlightAggShoppingContractTransportation.internal_static_com_ctrip_flight_agg_shopping_contract_transportation_PaxProductType_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ctrip.flight.agg.shopping.contract.transportation.ComCtripFlightAggShoppingContractTransportation.internal_static_com_ctrip_flight_agg_shopping_contract_transportation_PaxProductType_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ctrip.flight.agg.shopping.contract.transportation.PaxProductType.class, com.ctrip.flight.agg.shopping.contract.transportation.PaxProductType.Builder.class);
  }

  private int bitField0_;
  public static final int AGETYPE_FIELD_NUMBER = 1;
  private int ageType_;
  /**
   * <pre>
   * 乘客类型, 1: Adult; 2: Child; 4: Infant
   * </pre>
   *
   * <code>int32 AgeType = 1;</code>
   */
  public int getAgeType() {
    return ageType_;
  }

  public static final int SALECURRENCYPRICEDETAIL_FIELD_NUMBER = 2;
  private com.ctrip.flight.agg.shopping.contract.transportation.SaleCurrencyPriceDetailType saleCurrencyPriceDetail_;
  /**
   * <pre>
   * 销售币种的卖价
   * </pre>
   *
   * <code>.com.ctrip.flight.agg.shopping.contract.transportation.SaleCurrencyPriceDetailType SaleCurrencyPriceDetail = 2;</code>
   */
  public boolean hasSaleCurrencyPriceDetail() {
    return saleCurrencyPriceDetail_ != null;
  }
  /**
   * <pre>
   * 销售币种的卖价
   * </pre>
   *
   * <code>.com.ctrip.flight.agg.shopping.contract.transportation.SaleCurrencyPriceDetailType SaleCurrencyPriceDetail = 2;</code>
   */
  public com.ctrip.flight.agg.shopping.contract.transportation.SaleCurrencyPriceDetailType getSaleCurrencyPriceDetail() {
    return saleCurrencyPriceDetail_ == null ? com.ctrip.flight.agg.shopping.contract.transportation.SaleCurrencyPriceDetailType.getDefaultInstance() : saleCurrencyPriceDetail_;
  }
  /**
   * <pre>
   * 销售币种的卖价
   * </pre>
   *
   * <code>.com.ctrip.flight.agg.shopping.contract.transportation.SaleCurrencyPriceDetailType SaleCurrencyPriceDetail = 2;</code>
   */
  public com.ctrip.flight.agg.shopping.contract.transportation.SaleCurrencyPriceDetailTypeOrBuilder getSaleCurrencyPriceDetailOrBuilder() {
    return getSaleCurrencyPriceDetail();
  }

  public static final int SETTLEMENTCURRENCYPRICEDETAIL_FIELD_NUMBER = 3;
  private com.ctrip.flight.agg.shopping.contract.transportation.SettlementCurrencyPriceDetailType settlementCurrencyPriceDetail_;
  /**
   * <pre>
   * 结算币种价格信息
   * </pre>
   *
   * <code>.com.ctrip.flight.agg.shopping.contract.transportation.SettlementCurrencyPriceDetailType SettlementCurrencyPriceDetail = 3;</code>
   */
  public boolean hasSettlementCurrencyPriceDetail() {
    return settlementCurrencyPriceDetail_ != null;
  }
  /**
   * <pre>
   * 结算币种价格信息
   * </pre>
   *
   * <code>.com.ctrip.flight.agg.shopping.contract.transportation.SettlementCurrencyPriceDetailType SettlementCurrencyPriceDetail = 3;</code>
   */
  public com.ctrip.flight.agg.shopping.contract.transportation.SettlementCurrencyPriceDetailType getSettlementCurrencyPriceDetail() {
    return settlementCurrencyPriceDetail_ == null ? com.ctrip.flight.agg.shopping.contract.transportation.SettlementCurrencyPriceDetailType.getDefaultInstance() : settlementCurrencyPriceDetail_;
  }
  /**
   * <pre>
   * 结算币种价格信息
   * </pre>
   *
   * <code>.com.ctrip.flight.agg.shopping.contract.transportation.SettlementCurrencyPriceDetailType SettlementCurrencyPriceDetail = 3;</code>
   */
  public com.ctrip.flight.agg.shopping.contract.transportation.SettlementCurrencyPriceDetailTypeOrBuilder getSettlementCurrencyPriceDetailOrBuilder() {
    return getSettlementCurrencyPriceDetail();
  }

  public static final int TAG_FIELD_NUMBER = 4;
  private java.util.List<com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType> tag_;
  /**
   * <pre>
   * 扩展结点
   * </pre>
   *
   * <code>repeated .com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType Tag = 4;</code>
   */
  public java.util.List<com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType> getTagList() {
    return tag_;
  }
  /**
   * <pre>
   * 扩展结点
   * </pre>
   *
   * <code>repeated .com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType Tag = 4;</code>
   */
  public java.util.List<? extends com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairTypeOrBuilder> 
      getTagOrBuilderList() {
    return tag_;
  }
  /**
   * <pre>
   * 扩展结点
   * </pre>
   *
   * <code>repeated .com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType Tag = 4;</code>
   */
  public int getTagCount() {
    return tag_.size();
  }
  /**
   * <pre>
   * 扩展结点
   * </pre>
   *
   * <code>repeated .com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType Tag = 4;</code>
   */
  public com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType getTag(int index) {
    return tag_.get(index);
  }
  /**
   * <pre>
   * 扩展结点
   * </pre>
   *
   * <code>repeated .com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType Tag = 4;</code>
   */
  public com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairTypeOrBuilder getTagOrBuilder(
      int index) {
    return tag_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (ageType_ != 0) {
      output.writeInt32(1, ageType_);
    }
    if (saleCurrencyPriceDetail_ != null) {
      output.writeMessage(2, getSaleCurrencyPriceDetail());
    }
    if (settlementCurrencyPriceDetail_ != null) {
      output.writeMessage(3, getSettlementCurrencyPriceDetail());
    }
    for (int i = 0; i < tag_.size(); i++) {
      output.writeMessage(4, tag_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (ageType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, ageType_);
    }
    if (saleCurrencyPriceDetail_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getSaleCurrencyPriceDetail());
    }
    if (settlementCurrencyPriceDetail_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getSettlementCurrencyPriceDetail());
    }
    for (int i = 0; i < tag_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, tag_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ctrip.flight.agg.shopping.contract.transportation.PaxProductType)) {
      return super.equals(obj);
    }
    com.ctrip.flight.agg.shopping.contract.transportation.PaxProductType other = (com.ctrip.flight.agg.shopping.contract.transportation.PaxProductType) obj;

    boolean result = true;
    result = result && (getAgeType()
        == other.getAgeType());
    result = result && (hasSaleCurrencyPriceDetail() == other.hasSaleCurrencyPriceDetail());
    if (hasSaleCurrencyPriceDetail()) {
      result = result && getSaleCurrencyPriceDetail()
          .equals(other.getSaleCurrencyPriceDetail());
    }
    result = result && (hasSettlementCurrencyPriceDetail() == other.hasSettlementCurrencyPriceDetail());
    if (hasSettlementCurrencyPriceDetail()) {
      result = result && getSettlementCurrencyPriceDetail()
          .equals(other.getSettlementCurrencyPriceDetail());
    }
    result = result && getTagList()
        .equals(other.getTagList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + AGETYPE_FIELD_NUMBER;
    hash = (53 * hash) + getAgeType();
    if (hasSaleCurrencyPriceDetail()) {
      hash = (37 * hash) + SALECURRENCYPRICEDETAIL_FIELD_NUMBER;
      hash = (53 * hash) + getSaleCurrencyPriceDetail().hashCode();
    }
    if (hasSettlementCurrencyPriceDetail()) {
      hash = (37 * hash) + SETTLEMENTCURRENCYPRICEDETAIL_FIELD_NUMBER;
      hash = (53 * hash) + getSettlementCurrencyPriceDetail().hashCode();
    }
    if (getTagCount() > 0) {
      hash = (37 * hash) + TAG_FIELD_NUMBER;
      hash = (53 * hash) + getTagList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ctrip.flight.agg.shopping.contract.transportation.PaxProductType parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ctrip.flight.agg.shopping.contract.transportation.PaxProductType parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ctrip.flight.agg.shopping.contract.transportation.PaxProductType parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ctrip.flight.agg.shopping.contract.transportation.PaxProductType parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ctrip.flight.agg.shopping.contract.transportation.PaxProductType parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ctrip.flight.agg.shopping.contract.transportation.PaxProductType parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ctrip.flight.agg.shopping.contract.transportation.PaxProductType parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ctrip.flight.agg.shopping.contract.transportation.PaxProductType parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ctrip.flight.agg.shopping.contract.transportation.PaxProductType parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ctrip.flight.agg.shopping.contract.transportation.PaxProductType parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ctrip.flight.agg.shopping.contract.transportation.PaxProductType parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ctrip.flight.agg.shopping.contract.transportation.PaxProductType parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ctrip.flight.agg.shopping.contract.transportation.PaxProductType prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.ctrip.flight.agg.shopping.contract.transportation.PaxProductType}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.ctrip.flight.agg.shopping.contract.transportation.PaxProductType)
      com.ctrip.flight.agg.shopping.contract.transportation.PaxProductTypeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ctrip.flight.agg.shopping.contract.transportation.ComCtripFlightAggShoppingContractTransportation.internal_static_com_ctrip_flight_agg_shopping_contract_transportation_PaxProductType_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ctrip.flight.agg.shopping.contract.transportation.ComCtripFlightAggShoppingContractTransportation.internal_static_com_ctrip_flight_agg_shopping_contract_transportation_PaxProductType_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ctrip.flight.agg.shopping.contract.transportation.PaxProductType.class, com.ctrip.flight.agg.shopping.contract.transportation.PaxProductType.Builder.class);
    }

    // Construct using com.ctrip.flight.agg.shopping.contract.transportation.PaxProductType.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getTagFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      ageType_ = 0;

      if (saleCurrencyPriceDetailBuilder_ == null) {
        saleCurrencyPriceDetail_ = null;
      } else {
        saleCurrencyPriceDetail_ = null;
        saleCurrencyPriceDetailBuilder_ = null;
      }
      if (settlementCurrencyPriceDetailBuilder_ == null) {
        settlementCurrencyPriceDetail_ = null;
      } else {
        settlementCurrencyPriceDetail_ = null;
        settlementCurrencyPriceDetailBuilder_ = null;
      }
      if (tagBuilder_ == null) {
        tag_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
      } else {
        tagBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ctrip.flight.agg.shopping.contract.transportation.ComCtripFlightAggShoppingContractTransportation.internal_static_com_ctrip_flight_agg_shopping_contract_transportation_PaxProductType_descriptor;
    }

    @java.lang.Override
    public com.ctrip.flight.agg.shopping.contract.transportation.PaxProductType getDefaultInstanceForType() {
      return com.ctrip.flight.agg.shopping.contract.transportation.PaxProductType.getDefaultInstance();
    }

    @java.lang.Override
    public com.ctrip.flight.agg.shopping.contract.transportation.PaxProductType build() {
      com.ctrip.flight.agg.shopping.contract.transportation.PaxProductType result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ctrip.flight.agg.shopping.contract.transportation.PaxProductType buildPartial() {
      com.ctrip.flight.agg.shopping.contract.transportation.PaxProductType result = new com.ctrip.flight.agg.shopping.contract.transportation.PaxProductType(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.ageType_ = ageType_;
      if (saleCurrencyPriceDetailBuilder_ == null) {
        result.saleCurrencyPriceDetail_ = saleCurrencyPriceDetail_;
      } else {
        result.saleCurrencyPriceDetail_ = saleCurrencyPriceDetailBuilder_.build();
      }
      if (settlementCurrencyPriceDetailBuilder_ == null) {
        result.settlementCurrencyPriceDetail_ = settlementCurrencyPriceDetail_;
      } else {
        result.settlementCurrencyPriceDetail_ = settlementCurrencyPriceDetailBuilder_.build();
      }
      if (tagBuilder_ == null) {
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          tag_ = java.util.Collections.unmodifiableList(tag_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.tag_ = tag_;
      } else {
        result.tag_ = tagBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ctrip.flight.agg.shopping.contract.transportation.PaxProductType) {
        return mergeFrom((com.ctrip.flight.agg.shopping.contract.transportation.PaxProductType)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ctrip.flight.agg.shopping.contract.transportation.PaxProductType other) {
      if (other == com.ctrip.flight.agg.shopping.contract.transportation.PaxProductType.getDefaultInstance()) return this;
      if (other.getAgeType() != 0) {
        setAgeType(other.getAgeType());
      }
      if (other.hasSaleCurrencyPriceDetail()) {
        mergeSaleCurrencyPriceDetail(other.getSaleCurrencyPriceDetail());
      }
      if (other.hasSettlementCurrencyPriceDetail()) {
        mergeSettlementCurrencyPriceDetail(other.getSettlementCurrencyPriceDetail());
      }
      if (tagBuilder_ == null) {
        if (!other.tag_.isEmpty()) {
          if (tag_.isEmpty()) {
            tag_ = other.tag_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureTagIsMutable();
            tag_.addAll(other.tag_);
          }
          onChanged();
        }
      } else {
        if (!other.tag_.isEmpty()) {
          if (tagBuilder_.isEmpty()) {
            tagBuilder_.dispose();
            tagBuilder_ = null;
            tag_ = other.tag_;
            bitField0_ = (bitField0_ & ~0x00000008);
            tagBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getTagFieldBuilder() : null;
          } else {
            tagBuilder_.addAllMessages(other.tag_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ctrip.flight.agg.shopping.contract.transportation.PaxProductType parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ctrip.flight.agg.shopping.contract.transportation.PaxProductType) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int ageType_ ;
    /**
     * <pre>
     * 乘客类型, 1: Adult; 2: Child; 4: Infant
     * </pre>
     *
     * <code>int32 AgeType = 1;</code>
     */
    public int getAgeType() {
      return ageType_;
    }
    /**
     * <pre>
     * 乘客类型, 1: Adult; 2: Child; 4: Infant
     * </pre>
     *
     * <code>int32 AgeType = 1;</code>
     */
    public Builder setAgeType(int value) {
      
      ageType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 乘客类型, 1: Adult; 2: Child; 4: Infant
     * </pre>
     *
     * <code>int32 AgeType = 1;</code>
     */
    public Builder clearAgeType() {
      
      ageType_ = 0;
      onChanged();
      return this;
    }

    private com.ctrip.flight.agg.shopping.contract.transportation.SaleCurrencyPriceDetailType saleCurrencyPriceDetail_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ctrip.flight.agg.shopping.contract.transportation.SaleCurrencyPriceDetailType, com.ctrip.flight.agg.shopping.contract.transportation.SaleCurrencyPriceDetailType.Builder, com.ctrip.flight.agg.shopping.contract.transportation.SaleCurrencyPriceDetailTypeOrBuilder> saleCurrencyPriceDetailBuilder_;
    /**
     * <pre>
     * 销售币种的卖价
     * </pre>
     *
     * <code>.com.ctrip.flight.agg.shopping.contract.transportation.SaleCurrencyPriceDetailType SaleCurrencyPriceDetail = 2;</code>
     */
    public boolean hasSaleCurrencyPriceDetail() {
      return saleCurrencyPriceDetailBuilder_ != null || saleCurrencyPriceDetail_ != null;
    }
    /**
     * <pre>
     * 销售币种的卖价
     * </pre>
     *
     * <code>.com.ctrip.flight.agg.shopping.contract.transportation.SaleCurrencyPriceDetailType SaleCurrencyPriceDetail = 2;</code>
     */
    public com.ctrip.flight.agg.shopping.contract.transportation.SaleCurrencyPriceDetailType getSaleCurrencyPriceDetail() {
      if (saleCurrencyPriceDetailBuilder_ == null) {
        return saleCurrencyPriceDetail_ == null ? com.ctrip.flight.agg.shopping.contract.transportation.SaleCurrencyPriceDetailType.getDefaultInstance() : saleCurrencyPriceDetail_;
      } else {
        return saleCurrencyPriceDetailBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 销售币种的卖价
     * </pre>
     *
     * <code>.com.ctrip.flight.agg.shopping.contract.transportation.SaleCurrencyPriceDetailType SaleCurrencyPriceDetail = 2;</code>
     */
    public Builder setSaleCurrencyPriceDetail(com.ctrip.flight.agg.shopping.contract.transportation.SaleCurrencyPriceDetailType value) {
      if (saleCurrencyPriceDetailBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        saleCurrencyPriceDetail_ = value;
        onChanged();
      } else {
        saleCurrencyPriceDetailBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * 销售币种的卖价
     * </pre>
     *
     * <code>.com.ctrip.flight.agg.shopping.contract.transportation.SaleCurrencyPriceDetailType SaleCurrencyPriceDetail = 2;</code>
     */
    public Builder setSaleCurrencyPriceDetail(
        com.ctrip.flight.agg.shopping.contract.transportation.SaleCurrencyPriceDetailType.Builder builderForValue) {
      if (saleCurrencyPriceDetailBuilder_ == null) {
        saleCurrencyPriceDetail_ = builderForValue.build();
        onChanged();
      } else {
        saleCurrencyPriceDetailBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * 销售币种的卖价
     * </pre>
     *
     * <code>.com.ctrip.flight.agg.shopping.contract.transportation.SaleCurrencyPriceDetailType SaleCurrencyPriceDetail = 2;</code>
     */
    public Builder mergeSaleCurrencyPriceDetail(com.ctrip.flight.agg.shopping.contract.transportation.SaleCurrencyPriceDetailType value) {
      if (saleCurrencyPriceDetailBuilder_ == null) {
        if (saleCurrencyPriceDetail_ != null) {
          saleCurrencyPriceDetail_ =
            com.ctrip.flight.agg.shopping.contract.transportation.SaleCurrencyPriceDetailType.newBuilder(saleCurrencyPriceDetail_).mergeFrom(value).buildPartial();
        } else {
          saleCurrencyPriceDetail_ = value;
        }
        onChanged();
      } else {
        saleCurrencyPriceDetailBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * 销售币种的卖价
     * </pre>
     *
     * <code>.com.ctrip.flight.agg.shopping.contract.transportation.SaleCurrencyPriceDetailType SaleCurrencyPriceDetail = 2;</code>
     */
    public Builder clearSaleCurrencyPriceDetail() {
      if (saleCurrencyPriceDetailBuilder_ == null) {
        saleCurrencyPriceDetail_ = null;
        onChanged();
      } else {
        saleCurrencyPriceDetail_ = null;
        saleCurrencyPriceDetailBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * 销售币种的卖价
     * </pre>
     *
     * <code>.com.ctrip.flight.agg.shopping.contract.transportation.SaleCurrencyPriceDetailType SaleCurrencyPriceDetail = 2;</code>
     */
    public com.ctrip.flight.agg.shopping.contract.transportation.SaleCurrencyPriceDetailType.Builder getSaleCurrencyPriceDetailBuilder() {
      
      onChanged();
      return getSaleCurrencyPriceDetailFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 销售币种的卖价
     * </pre>
     *
     * <code>.com.ctrip.flight.agg.shopping.contract.transportation.SaleCurrencyPriceDetailType SaleCurrencyPriceDetail = 2;</code>
     */
    public com.ctrip.flight.agg.shopping.contract.transportation.SaleCurrencyPriceDetailTypeOrBuilder getSaleCurrencyPriceDetailOrBuilder() {
      if (saleCurrencyPriceDetailBuilder_ != null) {
        return saleCurrencyPriceDetailBuilder_.getMessageOrBuilder();
      } else {
        return saleCurrencyPriceDetail_ == null ?
            com.ctrip.flight.agg.shopping.contract.transportation.SaleCurrencyPriceDetailType.getDefaultInstance() : saleCurrencyPriceDetail_;
      }
    }
    /**
     * <pre>
     * 销售币种的卖价
     * </pre>
     *
     * <code>.com.ctrip.flight.agg.shopping.contract.transportation.SaleCurrencyPriceDetailType SaleCurrencyPriceDetail = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ctrip.flight.agg.shopping.contract.transportation.SaleCurrencyPriceDetailType, com.ctrip.flight.agg.shopping.contract.transportation.SaleCurrencyPriceDetailType.Builder, com.ctrip.flight.agg.shopping.contract.transportation.SaleCurrencyPriceDetailTypeOrBuilder> 
        getSaleCurrencyPriceDetailFieldBuilder() {
      if (saleCurrencyPriceDetailBuilder_ == null) {
        saleCurrencyPriceDetailBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.ctrip.flight.agg.shopping.contract.transportation.SaleCurrencyPriceDetailType, com.ctrip.flight.agg.shopping.contract.transportation.SaleCurrencyPriceDetailType.Builder, com.ctrip.flight.agg.shopping.contract.transportation.SaleCurrencyPriceDetailTypeOrBuilder>(
                getSaleCurrencyPriceDetail(),
                getParentForChildren(),
                isClean());
        saleCurrencyPriceDetail_ = null;
      }
      return saleCurrencyPriceDetailBuilder_;
    }

    private com.ctrip.flight.agg.shopping.contract.transportation.SettlementCurrencyPriceDetailType settlementCurrencyPriceDetail_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ctrip.flight.agg.shopping.contract.transportation.SettlementCurrencyPriceDetailType, com.ctrip.flight.agg.shopping.contract.transportation.SettlementCurrencyPriceDetailType.Builder, com.ctrip.flight.agg.shopping.contract.transportation.SettlementCurrencyPriceDetailTypeOrBuilder> settlementCurrencyPriceDetailBuilder_;
    /**
     * <pre>
     * 结算币种价格信息
     * </pre>
     *
     * <code>.com.ctrip.flight.agg.shopping.contract.transportation.SettlementCurrencyPriceDetailType SettlementCurrencyPriceDetail = 3;</code>
     */
    public boolean hasSettlementCurrencyPriceDetail() {
      return settlementCurrencyPriceDetailBuilder_ != null || settlementCurrencyPriceDetail_ != null;
    }
    /**
     * <pre>
     * 结算币种价格信息
     * </pre>
     *
     * <code>.com.ctrip.flight.agg.shopping.contract.transportation.SettlementCurrencyPriceDetailType SettlementCurrencyPriceDetail = 3;</code>
     */
    public com.ctrip.flight.agg.shopping.contract.transportation.SettlementCurrencyPriceDetailType getSettlementCurrencyPriceDetail() {
      if (settlementCurrencyPriceDetailBuilder_ == null) {
        return settlementCurrencyPriceDetail_ == null ? com.ctrip.flight.agg.shopping.contract.transportation.SettlementCurrencyPriceDetailType.getDefaultInstance() : settlementCurrencyPriceDetail_;
      } else {
        return settlementCurrencyPriceDetailBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 结算币种价格信息
     * </pre>
     *
     * <code>.com.ctrip.flight.agg.shopping.contract.transportation.SettlementCurrencyPriceDetailType SettlementCurrencyPriceDetail = 3;</code>
     */
    public Builder setSettlementCurrencyPriceDetail(com.ctrip.flight.agg.shopping.contract.transportation.SettlementCurrencyPriceDetailType value) {
      if (settlementCurrencyPriceDetailBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        settlementCurrencyPriceDetail_ = value;
        onChanged();
      } else {
        settlementCurrencyPriceDetailBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * 结算币种价格信息
     * </pre>
     *
     * <code>.com.ctrip.flight.agg.shopping.contract.transportation.SettlementCurrencyPriceDetailType SettlementCurrencyPriceDetail = 3;</code>
     */
    public Builder setSettlementCurrencyPriceDetail(
        com.ctrip.flight.agg.shopping.contract.transportation.SettlementCurrencyPriceDetailType.Builder builderForValue) {
      if (settlementCurrencyPriceDetailBuilder_ == null) {
        settlementCurrencyPriceDetail_ = builderForValue.build();
        onChanged();
      } else {
        settlementCurrencyPriceDetailBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * 结算币种价格信息
     * </pre>
     *
     * <code>.com.ctrip.flight.agg.shopping.contract.transportation.SettlementCurrencyPriceDetailType SettlementCurrencyPriceDetail = 3;</code>
     */
    public Builder mergeSettlementCurrencyPriceDetail(com.ctrip.flight.agg.shopping.contract.transportation.SettlementCurrencyPriceDetailType value) {
      if (settlementCurrencyPriceDetailBuilder_ == null) {
        if (settlementCurrencyPriceDetail_ != null) {
          settlementCurrencyPriceDetail_ =
            com.ctrip.flight.agg.shopping.contract.transportation.SettlementCurrencyPriceDetailType.newBuilder(settlementCurrencyPriceDetail_).mergeFrom(value).buildPartial();
        } else {
          settlementCurrencyPriceDetail_ = value;
        }
        onChanged();
      } else {
        settlementCurrencyPriceDetailBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * 结算币种价格信息
     * </pre>
     *
     * <code>.com.ctrip.flight.agg.shopping.contract.transportation.SettlementCurrencyPriceDetailType SettlementCurrencyPriceDetail = 3;</code>
     */
    public Builder clearSettlementCurrencyPriceDetail() {
      if (settlementCurrencyPriceDetailBuilder_ == null) {
        settlementCurrencyPriceDetail_ = null;
        onChanged();
      } else {
        settlementCurrencyPriceDetail_ = null;
        settlementCurrencyPriceDetailBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * 结算币种价格信息
     * </pre>
     *
     * <code>.com.ctrip.flight.agg.shopping.contract.transportation.SettlementCurrencyPriceDetailType SettlementCurrencyPriceDetail = 3;</code>
     */
    public com.ctrip.flight.agg.shopping.contract.transportation.SettlementCurrencyPriceDetailType.Builder getSettlementCurrencyPriceDetailBuilder() {
      
      onChanged();
      return getSettlementCurrencyPriceDetailFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 结算币种价格信息
     * </pre>
     *
     * <code>.com.ctrip.flight.agg.shopping.contract.transportation.SettlementCurrencyPriceDetailType SettlementCurrencyPriceDetail = 3;</code>
     */
    public com.ctrip.flight.agg.shopping.contract.transportation.SettlementCurrencyPriceDetailTypeOrBuilder getSettlementCurrencyPriceDetailOrBuilder() {
      if (settlementCurrencyPriceDetailBuilder_ != null) {
        return settlementCurrencyPriceDetailBuilder_.getMessageOrBuilder();
      } else {
        return settlementCurrencyPriceDetail_ == null ?
            com.ctrip.flight.agg.shopping.contract.transportation.SettlementCurrencyPriceDetailType.getDefaultInstance() : settlementCurrencyPriceDetail_;
      }
    }
    /**
     * <pre>
     * 结算币种价格信息
     * </pre>
     *
     * <code>.com.ctrip.flight.agg.shopping.contract.transportation.SettlementCurrencyPriceDetailType SettlementCurrencyPriceDetail = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ctrip.flight.agg.shopping.contract.transportation.SettlementCurrencyPriceDetailType, com.ctrip.flight.agg.shopping.contract.transportation.SettlementCurrencyPriceDetailType.Builder, com.ctrip.flight.agg.shopping.contract.transportation.SettlementCurrencyPriceDetailTypeOrBuilder> 
        getSettlementCurrencyPriceDetailFieldBuilder() {
      if (settlementCurrencyPriceDetailBuilder_ == null) {
        settlementCurrencyPriceDetailBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.ctrip.flight.agg.shopping.contract.transportation.SettlementCurrencyPriceDetailType, com.ctrip.flight.agg.shopping.contract.transportation.SettlementCurrencyPriceDetailType.Builder, com.ctrip.flight.agg.shopping.contract.transportation.SettlementCurrencyPriceDetailTypeOrBuilder>(
                getSettlementCurrencyPriceDetail(),
                getParentForChildren(),
                isClean());
        settlementCurrencyPriceDetail_ = null;
      }
      return settlementCurrencyPriceDetailBuilder_;
    }

    private java.util.List<com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType> tag_ =
      java.util.Collections.emptyList();
    private void ensureTagIsMutable() {
      if (!((bitField0_ & 0x00000008) == 0x00000008)) {
        tag_ = new java.util.ArrayList<com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType>(tag_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType, com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType.Builder, com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairTypeOrBuilder> tagBuilder_;

    /**
     * <pre>
     * 扩展结点
     * </pre>
     *
     * <code>repeated .com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType Tag = 4;</code>
     */
    public java.util.List<com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType> getTagList() {
      if (tagBuilder_ == null) {
        return java.util.Collections.unmodifiableList(tag_);
      } else {
        return tagBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * 扩展结点
     * </pre>
     *
     * <code>repeated .com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType Tag = 4;</code>
     */
    public int getTagCount() {
      if (tagBuilder_ == null) {
        return tag_.size();
      } else {
        return tagBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * 扩展结点
     * </pre>
     *
     * <code>repeated .com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType Tag = 4;</code>
     */
    public com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType getTag(int index) {
      if (tagBuilder_ == null) {
        return tag_.get(index);
      } else {
        return tagBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * 扩展结点
     * </pre>
     *
     * <code>repeated .com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType Tag = 4;</code>
     */
    public Builder setTag(
        int index, com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType value) {
      if (tagBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTagIsMutable();
        tag_.set(index, value);
        onChanged();
      } else {
        tagBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 扩展结点
     * </pre>
     *
     * <code>repeated .com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType Tag = 4;</code>
     */
    public Builder setTag(
        int index, com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType.Builder builderForValue) {
      if (tagBuilder_ == null) {
        ensureTagIsMutable();
        tag_.set(index, builderForValue.build());
        onChanged();
      } else {
        tagBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 扩展结点
     * </pre>
     *
     * <code>repeated .com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType Tag = 4;</code>
     */
    public Builder addTag(com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType value) {
      if (tagBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTagIsMutable();
        tag_.add(value);
        onChanged();
      } else {
        tagBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * 扩展结点
     * </pre>
     *
     * <code>repeated .com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType Tag = 4;</code>
     */
    public Builder addTag(
        int index, com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType value) {
      if (tagBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTagIsMutable();
        tag_.add(index, value);
        onChanged();
      } else {
        tagBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 扩展结点
     * </pre>
     *
     * <code>repeated .com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType Tag = 4;</code>
     */
    public Builder addTag(
        com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType.Builder builderForValue) {
      if (tagBuilder_ == null) {
        ensureTagIsMutable();
        tag_.add(builderForValue.build());
        onChanged();
      } else {
        tagBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 扩展结点
     * </pre>
     *
     * <code>repeated .com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType Tag = 4;</code>
     */
    public Builder addTag(
        int index, com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType.Builder builderForValue) {
      if (tagBuilder_ == null) {
        ensureTagIsMutable();
        tag_.add(index, builderForValue.build());
        onChanged();
      } else {
        tagBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 扩展结点
     * </pre>
     *
     * <code>repeated .com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType Tag = 4;</code>
     */
    public Builder addAllTag(
        java.lang.Iterable<? extends com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType> values) {
      if (tagBuilder_ == null) {
        ensureTagIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, tag_);
        onChanged();
      } else {
        tagBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * 扩展结点
     * </pre>
     *
     * <code>repeated .com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType Tag = 4;</code>
     */
    public Builder clearTag() {
      if (tagBuilder_ == null) {
        tag_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        tagBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 扩展结点
     * </pre>
     *
     * <code>repeated .com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType Tag = 4;</code>
     */
    public Builder removeTag(int index) {
      if (tagBuilder_ == null) {
        ensureTagIsMutable();
        tag_.remove(index);
        onChanged();
      } else {
        tagBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * 扩展结点
     * </pre>
     *
     * <code>repeated .com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType Tag = 4;</code>
     */
    public com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType.Builder getTagBuilder(
        int index) {
      return getTagFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * 扩展结点
     * </pre>
     *
     * <code>repeated .com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType Tag = 4;</code>
     */
    public com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairTypeOrBuilder getTagOrBuilder(
        int index) {
      if (tagBuilder_ == null) {
        return tag_.get(index);  } else {
        return tagBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * 扩展结点
     * </pre>
     *
     * <code>repeated .com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType Tag = 4;</code>
     */
    public java.util.List<? extends com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairTypeOrBuilder> 
         getTagOrBuilderList() {
      if (tagBuilder_ != null) {
        return tagBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(tag_);
      }
    }
    /**
     * <pre>
     * 扩展结点
     * </pre>
     *
     * <code>repeated .com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType Tag = 4;</code>
     */
    public com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType.Builder addTagBuilder() {
      return getTagFieldBuilder().addBuilder(
          com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType.getDefaultInstance());
    }
    /**
     * <pre>
     * 扩展结点
     * </pre>
     *
     * <code>repeated .com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType Tag = 4;</code>
     */
    public com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType.Builder addTagBuilder(
        int index) {
      return getTagFieldBuilder().addBuilder(
          index, com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType.getDefaultInstance());
    }
    /**
     * <pre>
     * 扩展结点
     * </pre>
     *
     * <code>repeated .com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType Tag = 4;</code>
     */
    public java.util.List<com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType.Builder> 
         getTagBuilderList() {
      return getTagFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType, com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType.Builder, com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairTypeOrBuilder> 
        getTagFieldBuilder() {
      if (tagBuilder_ == null) {
        tagBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType, com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairType.Builder, com.ctrip.flight.agg.shopping.contract.transportation.KeyValuePairTypeOrBuilder>(
                tag_,
                ((bitField0_ & 0x00000008) == 0x00000008),
                getParentForChildren(),
                isClean());
        tag_ = null;
      }
      return tagBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.ctrip.flight.agg.shopping.contract.transportation.PaxProductType)
  }

  // @@protoc_insertion_point(class_scope:com.ctrip.flight.agg.shopping.contract.transportation.PaxProductType)
  private static final com.ctrip.flight.agg.shopping.contract.transportation.PaxProductType DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ctrip.flight.agg.shopping.contract.transportation.PaxProductType();
  }

  public static com.ctrip.flight.agg.shopping.contract.transportation.PaxProductType getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PaxProductType>
      PARSER = new com.google.protobuf.AbstractParser<PaxProductType>() {
    @java.lang.Override
    public PaxProductType parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PaxProductType(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PaxProductType> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PaxProductType> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ctrip.flight.agg.shopping.contract.transportation.PaxProductType getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

