// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com.ctrip.flight.agg.shopping.contract.transportation.proto

package com.ctrip.flight.agg.shopping.contract.transportation;

/**
 * Protobuf type {@code com.ctrip.flight.agg.shopping.contract.transportation.PaxSeatType}
 */
public  final class PaxSeatType extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.ctrip.flight.agg.shopping.contract.transportation.PaxSeatType)
    PaxSeatTypeOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PaxSeatType.newBuilder() to construct.
  private PaxSeatType(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PaxSeatType() {
    ageTypeGroup_ = 0;
    seatCount_ = 0;
    productDetailIndex_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PaxSeatType(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            ageTypeGroup_ = input.readInt32();
            break;
          }
          case 16: {

            seatCount_ = input.readInt32();
            break;
          }
          case 24: {

            productDetailIndex_ = input.readInt32();
            break;
          }
          case 34: {
            com.ctrip.flight.agg.shopping.contract.transportation.FlightSeatType.Builder subBuilder = null;
            if (flightSeat_ != null) {
              subBuilder = flightSeat_.toBuilder();
            }
            flightSeat_ = input.readMessage(com.ctrip.flight.agg.shopping.contract.transportation.FlightSeatType.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(flightSeat_);
              flightSeat_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            com.ctrip.flight.agg.shopping.contract.transportation.TrainSeatType.Builder subBuilder = null;
            if (trainSeat_ != null) {
              subBuilder = trainSeat_.toBuilder();
            }
            trainSeat_ = input.readMessage(com.ctrip.flight.agg.shopping.contract.transportation.TrainSeatType.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(trainSeat_);
              trainSeat_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ctrip.flight.agg.shopping.contract.transportation.ComCtripFlightAggShoppingContractTransportation.internal_static_com_ctrip_flight_agg_shopping_contract_transportation_PaxSeatType_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ctrip.flight.agg.shopping.contract.transportation.ComCtripFlightAggShoppingContractTransportation.internal_static_com_ctrip_flight_agg_shopping_contract_transportation_PaxSeatType_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ctrip.flight.agg.shopping.contract.transportation.PaxSeatType.class, com.ctrip.flight.agg.shopping.contract.transportation.PaxSeatType.Builder.class);
  }

  public static final int AGETYPEGROUP_FIELD_NUMBER = 1;
  private int ageTypeGroup_;
  /**
   * <pre>
   * 对应的乘客类型组，可表示多个乘客类型。1: Adult; 2: Child; 4: Infant;
   * </pre>
   *
   * <code>int32 AgeTypeGroup = 1;</code>
   */
  public int getAgeTypeGroup() {
    return ageTypeGroup_;
  }

  public static final int SEATCOUNT_FIELD_NUMBER = 2;
  private int seatCount_;
  /**
   * <pre>
   * 余票数量，国内机票的婴儿票则始终为10
   * </pre>
   *
   * <code>int32 SeatCount = 2;</code>
   */
  public int getSeatCount() {
    return seatCount_;
  }

  public static final int PRODUCTDETAILINDEX_FIELD_NUMBER = 3;
  private int productDetailIndex_;
  /**
   * <pre>
   * 与ProductDetailList的下标关联, 从0开始
   * </pre>
   *
   * <code>int32 ProductDetailIndex = 3;</code>
   */
  public int getProductDetailIndex() {
    return productDetailIndex_;
  }

  public static final int FLIGHTSEAT_FIELD_NUMBER = 4;
  private com.ctrip.flight.agg.shopping.contract.transportation.FlightSeatType flightSeat_;
  /**
   * <pre>
   * 机票舱位及相关信息
   * </pre>
   *
   * <code>.com.ctrip.flight.agg.shopping.contract.transportation.FlightSeatType FlightSeat = 4;</code>
   */
  public boolean hasFlightSeat() {
    return flightSeat_ != null;
  }
  /**
   * <pre>
   * 机票舱位及相关信息
   * </pre>
   *
   * <code>.com.ctrip.flight.agg.shopping.contract.transportation.FlightSeatType FlightSeat = 4;</code>
   */
  public com.ctrip.flight.agg.shopping.contract.transportation.FlightSeatType getFlightSeat() {
    return flightSeat_ == null ? com.ctrip.flight.agg.shopping.contract.transportation.FlightSeatType.getDefaultInstance() : flightSeat_;
  }
  /**
   * <pre>
   * 机票舱位及相关信息
   * </pre>
   *
   * <code>.com.ctrip.flight.agg.shopping.contract.transportation.FlightSeatType FlightSeat = 4;</code>
   */
  public com.ctrip.flight.agg.shopping.contract.transportation.FlightSeatTypeOrBuilder getFlightSeatOrBuilder() {
    return getFlightSeat();
  }

  public static final int TRAINSEAT_FIELD_NUMBER = 5;
  private com.ctrip.flight.agg.shopping.contract.transportation.TrainSeatType trainSeat_;
  /**
   * <pre>
   * 火车座位及相关信息
   * </pre>
   *
   * <code>.com.ctrip.flight.agg.shopping.contract.transportation.TrainSeatType TrainSeat = 5;</code>
   */
  public boolean hasTrainSeat() {
    return trainSeat_ != null;
  }
  /**
   * <pre>
   * 火车座位及相关信息
   * </pre>
   *
   * <code>.com.ctrip.flight.agg.shopping.contract.transportation.TrainSeatType TrainSeat = 5;</code>
   */
  public com.ctrip.flight.agg.shopping.contract.transportation.TrainSeatType getTrainSeat() {
    return trainSeat_ == null ? com.ctrip.flight.agg.shopping.contract.transportation.TrainSeatType.getDefaultInstance() : trainSeat_;
  }
  /**
   * <pre>
   * 火车座位及相关信息
   * </pre>
   *
   * <code>.com.ctrip.flight.agg.shopping.contract.transportation.TrainSeatType TrainSeat = 5;</code>
   */
  public com.ctrip.flight.agg.shopping.contract.transportation.TrainSeatTypeOrBuilder getTrainSeatOrBuilder() {
    return getTrainSeat();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (ageTypeGroup_ != 0) {
      output.writeInt32(1, ageTypeGroup_);
    }
    if (seatCount_ != 0) {
      output.writeInt32(2, seatCount_);
    }
    if (productDetailIndex_ != 0) {
      output.writeInt32(3, productDetailIndex_);
    }
    if (flightSeat_ != null) {
      output.writeMessage(4, getFlightSeat());
    }
    if (trainSeat_ != null) {
      output.writeMessage(5, getTrainSeat());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (ageTypeGroup_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, ageTypeGroup_);
    }
    if (seatCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, seatCount_);
    }
    if (productDetailIndex_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, productDetailIndex_);
    }
    if (flightSeat_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getFlightSeat());
    }
    if (trainSeat_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getTrainSeat());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ctrip.flight.agg.shopping.contract.transportation.PaxSeatType)) {
      return super.equals(obj);
    }
    com.ctrip.flight.agg.shopping.contract.transportation.PaxSeatType other = (com.ctrip.flight.agg.shopping.contract.transportation.PaxSeatType) obj;

    boolean result = true;
    result = result && (getAgeTypeGroup()
        == other.getAgeTypeGroup());
    result = result && (getSeatCount()
        == other.getSeatCount());
    result = result && (getProductDetailIndex()
        == other.getProductDetailIndex());
    result = result && (hasFlightSeat() == other.hasFlightSeat());
    if (hasFlightSeat()) {
      result = result && getFlightSeat()
          .equals(other.getFlightSeat());
    }
    result = result && (hasTrainSeat() == other.hasTrainSeat());
    if (hasTrainSeat()) {
      result = result && getTrainSeat()
          .equals(other.getTrainSeat());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + AGETYPEGROUP_FIELD_NUMBER;
    hash = (53 * hash) + getAgeTypeGroup();
    hash = (37 * hash) + SEATCOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getSeatCount();
    hash = (37 * hash) + PRODUCTDETAILINDEX_FIELD_NUMBER;
    hash = (53 * hash) + getProductDetailIndex();
    if (hasFlightSeat()) {
      hash = (37 * hash) + FLIGHTSEAT_FIELD_NUMBER;
      hash = (53 * hash) + getFlightSeat().hashCode();
    }
    if (hasTrainSeat()) {
      hash = (37 * hash) + TRAINSEAT_FIELD_NUMBER;
      hash = (53 * hash) + getTrainSeat().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ctrip.flight.agg.shopping.contract.transportation.PaxSeatType parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ctrip.flight.agg.shopping.contract.transportation.PaxSeatType parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ctrip.flight.agg.shopping.contract.transportation.PaxSeatType parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ctrip.flight.agg.shopping.contract.transportation.PaxSeatType parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ctrip.flight.agg.shopping.contract.transportation.PaxSeatType parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ctrip.flight.agg.shopping.contract.transportation.PaxSeatType parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ctrip.flight.agg.shopping.contract.transportation.PaxSeatType parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ctrip.flight.agg.shopping.contract.transportation.PaxSeatType parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ctrip.flight.agg.shopping.contract.transportation.PaxSeatType parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ctrip.flight.agg.shopping.contract.transportation.PaxSeatType parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ctrip.flight.agg.shopping.contract.transportation.PaxSeatType parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ctrip.flight.agg.shopping.contract.transportation.PaxSeatType parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ctrip.flight.agg.shopping.contract.transportation.PaxSeatType prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.ctrip.flight.agg.shopping.contract.transportation.PaxSeatType}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.ctrip.flight.agg.shopping.contract.transportation.PaxSeatType)
      com.ctrip.flight.agg.shopping.contract.transportation.PaxSeatTypeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ctrip.flight.agg.shopping.contract.transportation.ComCtripFlightAggShoppingContractTransportation.internal_static_com_ctrip_flight_agg_shopping_contract_transportation_PaxSeatType_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ctrip.flight.agg.shopping.contract.transportation.ComCtripFlightAggShoppingContractTransportation.internal_static_com_ctrip_flight_agg_shopping_contract_transportation_PaxSeatType_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ctrip.flight.agg.shopping.contract.transportation.PaxSeatType.class, com.ctrip.flight.agg.shopping.contract.transportation.PaxSeatType.Builder.class);
    }

    // Construct using com.ctrip.flight.agg.shopping.contract.transportation.PaxSeatType.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      ageTypeGroup_ = 0;

      seatCount_ = 0;

      productDetailIndex_ = 0;

      if (flightSeatBuilder_ == null) {
        flightSeat_ = null;
      } else {
        flightSeat_ = null;
        flightSeatBuilder_ = null;
      }
      if (trainSeatBuilder_ == null) {
        trainSeat_ = null;
      } else {
        trainSeat_ = null;
        trainSeatBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ctrip.flight.agg.shopping.contract.transportation.ComCtripFlightAggShoppingContractTransportation.internal_static_com_ctrip_flight_agg_shopping_contract_transportation_PaxSeatType_descriptor;
    }

    @java.lang.Override
    public com.ctrip.flight.agg.shopping.contract.transportation.PaxSeatType getDefaultInstanceForType() {
      return com.ctrip.flight.agg.shopping.contract.transportation.PaxSeatType.getDefaultInstance();
    }

    @java.lang.Override
    public com.ctrip.flight.agg.shopping.contract.transportation.PaxSeatType build() {
      com.ctrip.flight.agg.shopping.contract.transportation.PaxSeatType result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ctrip.flight.agg.shopping.contract.transportation.PaxSeatType buildPartial() {
      com.ctrip.flight.agg.shopping.contract.transportation.PaxSeatType result = new com.ctrip.flight.agg.shopping.contract.transportation.PaxSeatType(this);
      result.ageTypeGroup_ = ageTypeGroup_;
      result.seatCount_ = seatCount_;
      result.productDetailIndex_ = productDetailIndex_;
      if (flightSeatBuilder_ == null) {
        result.flightSeat_ = flightSeat_;
      } else {
        result.flightSeat_ = flightSeatBuilder_.build();
      }
      if (trainSeatBuilder_ == null) {
        result.trainSeat_ = trainSeat_;
      } else {
        result.trainSeat_ = trainSeatBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ctrip.flight.agg.shopping.contract.transportation.PaxSeatType) {
        return mergeFrom((com.ctrip.flight.agg.shopping.contract.transportation.PaxSeatType)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ctrip.flight.agg.shopping.contract.transportation.PaxSeatType other) {
      if (other == com.ctrip.flight.agg.shopping.contract.transportation.PaxSeatType.getDefaultInstance()) return this;
      if (other.getAgeTypeGroup() != 0) {
        setAgeTypeGroup(other.getAgeTypeGroup());
      }
      if (other.getSeatCount() != 0) {
        setSeatCount(other.getSeatCount());
      }
      if (other.getProductDetailIndex() != 0) {
        setProductDetailIndex(other.getProductDetailIndex());
      }
      if (other.hasFlightSeat()) {
        mergeFlightSeat(other.getFlightSeat());
      }
      if (other.hasTrainSeat()) {
        mergeTrainSeat(other.getTrainSeat());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ctrip.flight.agg.shopping.contract.transportation.PaxSeatType parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ctrip.flight.agg.shopping.contract.transportation.PaxSeatType) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int ageTypeGroup_ ;
    /**
     * <pre>
     * 对应的乘客类型组，可表示多个乘客类型。1: Adult; 2: Child; 4: Infant;
     * </pre>
     *
     * <code>int32 AgeTypeGroup = 1;</code>
     */
    public int getAgeTypeGroup() {
      return ageTypeGroup_;
    }
    /**
     * <pre>
     * 对应的乘客类型组，可表示多个乘客类型。1: Adult; 2: Child; 4: Infant;
     * </pre>
     *
     * <code>int32 AgeTypeGroup = 1;</code>
     */
    public Builder setAgeTypeGroup(int value) {
      
      ageTypeGroup_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 对应的乘客类型组，可表示多个乘客类型。1: Adult; 2: Child; 4: Infant;
     * </pre>
     *
     * <code>int32 AgeTypeGroup = 1;</code>
     */
    public Builder clearAgeTypeGroup() {
      
      ageTypeGroup_ = 0;
      onChanged();
      return this;
    }

    private int seatCount_ ;
    /**
     * <pre>
     * 余票数量，国内机票的婴儿票则始终为10
     * </pre>
     *
     * <code>int32 SeatCount = 2;</code>
     */
    public int getSeatCount() {
      return seatCount_;
    }
    /**
     * <pre>
     * 余票数量，国内机票的婴儿票则始终为10
     * </pre>
     *
     * <code>int32 SeatCount = 2;</code>
     */
    public Builder setSeatCount(int value) {
      
      seatCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 余票数量，国内机票的婴儿票则始终为10
     * </pre>
     *
     * <code>int32 SeatCount = 2;</code>
     */
    public Builder clearSeatCount() {
      
      seatCount_ = 0;
      onChanged();
      return this;
    }

    private int productDetailIndex_ ;
    /**
     * <pre>
     * 与ProductDetailList的下标关联, 从0开始
     * </pre>
     *
     * <code>int32 ProductDetailIndex = 3;</code>
     */
    public int getProductDetailIndex() {
      return productDetailIndex_;
    }
    /**
     * <pre>
     * 与ProductDetailList的下标关联, 从0开始
     * </pre>
     *
     * <code>int32 ProductDetailIndex = 3;</code>
     */
    public Builder setProductDetailIndex(int value) {
      
      productDetailIndex_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 与ProductDetailList的下标关联, 从0开始
     * </pre>
     *
     * <code>int32 ProductDetailIndex = 3;</code>
     */
    public Builder clearProductDetailIndex() {
      
      productDetailIndex_ = 0;
      onChanged();
      return this;
    }

    private com.ctrip.flight.agg.shopping.contract.transportation.FlightSeatType flightSeat_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ctrip.flight.agg.shopping.contract.transportation.FlightSeatType, com.ctrip.flight.agg.shopping.contract.transportation.FlightSeatType.Builder, com.ctrip.flight.agg.shopping.contract.transportation.FlightSeatTypeOrBuilder> flightSeatBuilder_;
    /**
     * <pre>
     * 机票舱位及相关信息
     * </pre>
     *
     * <code>.com.ctrip.flight.agg.shopping.contract.transportation.FlightSeatType FlightSeat = 4;</code>
     */
    public boolean hasFlightSeat() {
      return flightSeatBuilder_ != null || flightSeat_ != null;
    }
    /**
     * <pre>
     * 机票舱位及相关信息
     * </pre>
     *
     * <code>.com.ctrip.flight.agg.shopping.contract.transportation.FlightSeatType FlightSeat = 4;</code>
     */
    public com.ctrip.flight.agg.shopping.contract.transportation.FlightSeatType getFlightSeat() {
      if (flightSeatBuilder_ == null) {
        return flightSeat_ == null ? com.ctrip.flight.agg.shopping.contract.transportation.FlightSeatType.getDefaultInstance() : flightSeat_;
      } else {
        return flightSeatBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 机票舱位及相关信息
     * </pre>
     *
     * <code>.com.ctrip.flight.agg.shopping.contract.transportation.FlightSeatType FlightSeat = 4;</code>
     */
    public Builder setFlightSeat(com.ctrip.flight.agg.shopping.contract.transportation.FlightSeatType value) {
      if (flightSeatBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        flightSeat_ = value;
        onChanged();
      } else {
        flightSeatBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * 机票舱位及相关信息
     * </pre>
     *
     * <code>.com.ctrip.flight.agg.shopping.contract.transportation.FlightSeatType FlightSeat = 4;</code>
     */
    public Builder setFlightSeat(
        com.ctrip.flight.agg.shopping.contract.transportation.FlightSeatType.Builder builderForValue) {
      if (flightSeatBuilder_ == null) {
        flightSeat_ = builderForValue.build();
        onChanged();
      } else {
        flightSeatBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * 机票舱位及相关信息
     * </pre>
     *
     * <code>.com.ctrip.flight.agg.shopping.contract.transportation.FlightSeatType FlightSeat = 4;</code>
     */
    public Builder mergeFlightSeat(com.ctrip.flight.agg.shopping.contract.transportation.FlightSeatType value) {
      if (flightSeatBuilder_ == null) {
        if (flightSeat_ != null) {
          flightSeat_ =
            com.ctrip.flight.agg.shopping.contract.transportation.FlightSeatType.newBuilder(flightSeat_).mergeFrom(value).buildPartial();
        } else {
          flightSeat_ = value;
        }
        onChanged();
      } else {
        flightSeatBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * 机票舱位及相关信息
     * </pre>
     *
     * <code>.com.ctrip.flight.agg.shopping.contract.transportation.FlightSeatType FlightSeat = 4;</code>
     */
    public Builder clearFlightSeat() {
      if (flightSeatBuilder_ == null) {
        flightSeat_ = null;
        onChanged();
      } else {
        flightSeat_ = null;
        flightSeatBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * 机票舱位及相关信息
     * </pre>
     *
     * <code>.com.ctrip.flight.agg.shopping.contract.transportation.FlightSeatType FlightSeat = 4;</code>
     */
    public com.ctrip.flight.agg.shopping.contract.transportation.FlightSeatType.Builder getFlightSeatBuilder() {
      
      onChanged();
      return getFlightSeatFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 机票舱位及相关信息
     * </pre>
     *
     * <code>.com.ctrip.flight.agg.shopping.contract.transportation.FlightSeatType FlightSeat = 4;</code>
     */
    public com.ctrip.flight.agg.shopping.contract.transportation.FlightSeatTypeOrBuilder getFlightSeatOrBuilder() {
      if (flightSeatBuilder_ != null) {
        return flightSeatBuilder_.getMessageOrBuilder();
      } else {
        return flightSeat_ == null ?
            com.ctrip.flight.agg.shopping.contract.transportation.FlightSeatType.getDefaultInstance() : flightSeat_;
      }
    }
    /**
     * <pre>
     * 机票舱位及相关信息
     * </pre>
     *
     * <code>.com.ctrip.flight.agg.shopping.contract.transportation.FlightSeatType FlightSeat = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ctrip.flight.agg.shopping.contract.transportation.FlightSeatType, com.ctrip.flight.agg.shopping.contract.transportation.FlightSeatType.Builder, com.ctrip.flight.agg.shopping.contract.transportation.FlightSeatTypeOrBuilder> 
        getFlightSeatFieldBuilder() {
      if (flightSeatBuilder_ == null) {
        flightSeatBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.ctrip.flight.agg.shopping.contract.transportation.FlightSeatType, com.ctrip.flight.agg.shopping.contract.transportation.FlightSeatType.Builder, com.ctrip.flight.agg.shopping.contract.transportation.FlightSeatTypeOrBuilder>(
                getFlightSeat(),
                getParentForChildren(),
                isClean());
        flightSeat_ = null;
      }
      return flightSeatBuilder_;
    }

    private com.ctrip.flight.agg.shopping.contract.transportation.TrainSeatType trainSeat_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ctrip.flight.agg.shopping.contract.transportation.TrainSeatType, com.ctrip.flight.agg.shopping.contract.transportation.TrainSeatType.Builder, com.ctrip.flight.agg.shopping.contract.transportation.TrainSeatTypeOrBuilder> trainSeatBuilder_;
    /**
     * <pre>
     * 火车座位及相关信息
     * </pre>
     *
     * <code>.com.ctrip.flight.agg.shopping.contract.transportation.TrainSeatType TrainSeat = 5;</code>
     */
    public boolean hasTrainSeat() {
      return trainSeatBuilder_ != null || trainSeat_ != null;
    }
    /**
     * <pre>
     * 火车座位及相关信息
     * </pre>
     *
     * <code>.com.ctrip.flight.agg.shopping.contract.transportation.TrainSeatType TrainSeat = 5;</code>
     */
    public com.ctrip.flight.agg.shopping.contract.transportation.TrainSeatType getTrainSeat() {
      if (trainSeatBuilder_ == null) {
        return trainSeat_ == null ? com.ctrip.flight.agg.shopping.contract.transportation.TrainSeatType.getDefaultInstance() : trainSeat_;
      } else {
        return trainSeatBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 火车座位及相关信息
     * </pre>
     *
     * <code>.com.ctrip.flight.agg.shopping.contract.transportation.TrainSeatType TrainSeat = 5;</code>
     */
    public Builder setTrainSeat(com.ctrip.flight.agg.shopping.contract.transportation.TrainSeatType value) {
      if (trainSeatBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        trainSeat_ = value;
        onChanged();
      } else {
        trainSeatBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * 火车座位及相关信息
     * </pre>
     *
     * <code>.com.ctrip.flight.agg.shopping.contract.transportation.TrainSeatType TrainSeat = 5;</code>
     */
    public Builder setTrainSeat(
        com.ctrip.flight.agg.shopping.contract.transportation.TrainSeatType.Builder builderForValue) {
      if (trainSeatBuilder_ == null) {
        trainSeat_ = builderForValue.build();
        onChanged();
      } else {
        trainSeatBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * 火车座位及相关信息
     * </pre>
     *
     * <code>.com.ctrip.flight.agg.shopping.contract.transportation.TrainSeatType TrainSeat = 5;</code>
     */
    public Builder mergeTrainSeat(com.ctrip.flight.agg.shopping.contract.transportation.TrainSeatType value) {
      if (trainSeatBuilder_ == null) {
        if (trainSeat_ != null) {
          trainSeat_ =
            com.ctrip.flight.agg.shopping.contract.transportation.TrainSeatType.newBuilder(trainSeat_).mergeFrom(value).buildPartial();
        } else {
          trainSeat_ = value;
        }
        onChanged();
      } else {
        trainSeatBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * 火车座位及相关信息
     * </pre>
     *
     * <code>.com.ctrip.flight.agg.shopping.contract.transportation.TrainSeatType TrainSeat = 5;</code>
     */
    public Builder clearTrainSeat() {
      if (trainSeatBuilder_ == null) {
        trainSeat_ = null;
        onChanged();
      } else {
        trainSeat_ = null;
        trainSeatBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * 火车座位及相关信息
     * </pre>
     *
     * <code>.com.ctrip.flight.agg.shopping.contract.transportation.TrainSeatType TrainSeat = 5;</code>
     */
    public com.ctrip.flight.agg.shopping.contract.transportation.TrainSeatType.Builder getTrainSeatBuilder() {
      
      onChanged();
      return getTrainSeatFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 火车座位及相关信息
     * </pre>
     *
     * <code>.com.ctrip.flight.agg.shopping.contract.transportation.TrainSeatType TrainSeat = 5;</code>
     */
    public com.ctrip.flight.agg.shopping.contract.transportation.TrainSeatTypeOrBuilder getTrainSeatOrBuilder() {
      if (trainSeatBuilder_ != null) {
        return trainSeatBuilder_.getMessageOrBuilder();
      } else {
        return trainSeat_ == null ?
            com.ctrip.flight.agg.shopping.contract.transportation.TrainSeatType.getDefaultInstance() : trainSeat_;
      }
    }
    /**
     * <pre>
     * 火车座位及相关信息
     * </pre>
     *
     * <code>.com.ctrip.flight.agg.shopping.contract.transportation.TrainSeatType TrainSeat = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ctrip.flight.agg.shopping.contract.transportation.TrainSeatType, com.ctrip.flight.agg.shopping.contract.transportation.TrainSeatType.Builder, com.ctrip.flight.agg.shopping.contract.transportation.TrainSeatTypeOrBuilder> 
        getTrainSeatFieldBuilder() {
      if (trainSeatBuilder_ == null) {
        trainSeatBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.ctrip.flight.agg.shopping.contract.transportation.TrainSeatType, com.ctrip.flight.agg.shopping.contract.transportation.TrainSeatType.Builder, com.ctrip.flight.agg.shopping.contract.transportation.TrainSeatTypeOrBuilder>(
                getTrainSeat(),
                getParentForChildren(),
                isClean());
        trainSeat_ = null;
      }
      return trainSeatBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.ctrip.flight.agg.shopping.contract.transportation.PaxSeatType)
  }

  // @@protoc_insertion_point(class_scope:com.ctrip.flight.agg.shopping.contract.transportation.PaxSeatType)
  private static final com.ctrip.flight.agg.shopping.contract.transportation.PaxSeatType DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ctrip.flight.agg.shopping.contract.transportation.PaxSeatType();
  }

  public static com.ctrip.flight.agg.shopping.contract.transportation.PaxSeatType getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PaxSeatType>
      PARSER = new com.google.protobuf.AbstractParser<PaxSeatType>() {
    @java.lang.Override
    public PaxSeatType parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PaxSeatType(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PaxSeatType> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PaxSeatType> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ctrip.flight.agg.shopping.contract.transportation.PaxSeatType getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

