// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com.ctrip.flight.agg.shopping.contract.transportation.proto

package com.ctrip.flight.agg.shopping.contract.transportation;

public interface RBDDisclosureTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ctrip.flight.agg.shopping.contract.transportation.RBDDisclosureType)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 舱位名称
   * </pre>
   *
   * <code>string Name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <pre>
   * 舱位名称
   * </pre>
   *
   * <code>string Name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * 舱位简称
   * </pre>
   *
   * <code>string ShortName = 2;</code>
   */
  java.lang.String getShortName();
  /**
   * <pre>
   * 舱位简称
   * </pre>
   *
   * <code>string ShortName = 2;</code>
   */
  com.google.protobuf.ByteString
      getShortNameBytes();

  /**
   * <pre>
   * 舱位描述
   * </pre>
   *
   * <code>string Description = 3;</code>
   */
  java.lang.String getDescription();
  /**
   * <pre>
   * 舱位描述
   * </pre>
   *
   * <code>string Description = 3;</code>
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();
}
