// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com.ctrip.flight.agg.shopping.contract.transportation.proto

package com.ctrip.flight.agg.shopping.contract.transportation;

public interface UpgradeTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ctrip.flight.agg.shopping.contract.transportation.UpgradeType)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 索引id
   * </pre>
   *
   * <code>int32 RefNum = 1;</code>
   */
  int getRefNum();

  /**
   * <pre>
   * 主政策ID
   * </pre>
   *
   * <code>int64 PolicyID = 2;</code>
   */
  long getPolicyID();

  /**
   * <pre>
   * 舱等，YCF
   * </pre>
   *
   * <code>string CabinCode = 3;</code>
   */
  java.lang.String getCabinCode();
  /**
   * <pre>
   * 舱等，YCF
   * </pre>
   *
   * <code>string CabinCode = 3;</code>
   */
  com.google.protobuf.ByteString
      getCabinCodeBytes();

  /**
   * <pre>
   * 可升舱舱位
   * </pre>
   *
   * <code>string RBD = 4;</code>
   */
  java.lang.String getRBD();
  /**
   * <pre>
   * 可升舱舱位
   * </pre>
   *
   * <code>string RBD = 4;</code>
   */
  com.google.protobuf.ByteString
      getRBDBytes();

  /**
   * <pre>
   * 特殊舱位
   * </pre>
   *
   * <code>.com.ctrip.flight.agg.shopping.contract.transportation.RBDDisclosureType RBDDisclosure = 5;</code>
   */
  boolean hasRBDDisclosure();
  /**
   * <pre>
   * 特殊舱位
   * </pre>
   *
   * <code>.com.ctrip.flight.agg.shopping.contract.transportation.RBDDisclosureType RBDDisclosure = 5;</code>
   */
  com.ctrip.flight.agg.shopping.contract.transportation.RBDDisclosureType getRBDDisclosure();
  /**
   * <pre>
   * 特殊舱位
   * </pre>
   *
   * <code>.com.ctrip.flight.agg.shopping.contract.transportation.RBDDisclosureType RBDDisclosure = 5;</code>
   */
  com.ctrip.flight.agg.shopping.contract.transportation.RBDDisclosureTypeOrBuilder getRBDDisclosureOrBuilder();

  /**
   * <pre>
   * 升舱价格
   * </pre>
   *
   * <code>double SalePrice = 6;</code>
   */
  double getSalePrice();

  /**
   * <pre>
   * 原票面价
   * </pre>
   *
   * <code>double OriginalPublishPrice = 7;</code>
   */
  double getOriginalPublishPrice();

  /**
   * <pre>
   * 库存
   * </pre>
   *
   * <code>int32 SeatCount = 8;</code>
   */
  int getSeatCount();

  /**
   * <pre>
   * 升舱后报销凭证
   * </pre>
   *
   * <code>int32 InvoiceType = 9;</code>
   */
  int getInvoiceType();

  /**
   * <pre>
   * 餐食标识 T/F
   * </pre>
   *
   * <code>string MealFlag = 10;</code>
   */
  java.lang.String getMealFlag();
  /**
   * <pre>
   * 餐食标识 T/F
   * </pre>
   *
   * <code>string MealFlag = 10;</code>
   */
  com.google.protobuf.ByteString
      getMealFlagBytes();

  /**
   * <pre>
   * 行李额类型，1按两舱，2按经济舱
   * </pre>
   *
   * <code>int32 BaggageType = 11;</code>
   */
  int getBaggageType();

  /**
   * <pre>
   * 里程类型，1按两舱，2按经济舱
   * </pre>
   *
   * <code>int32 MileageType = 12;</code>
   */
  int getMileageType();

  /**
   * <pre>
   * 升舱退改签RCKey
   * </pre>
   *
   * <code>string CompatiblePenaltyKey = 13;</code>
   */
  java.lang.String getCompatiblePenaltyKey();
  /**
   * <pre>
   * 升舱退改签RCKey
   * </pre>
   *
   * <code>string CompatiblePenaltyKey = 13;</code>
   */
  com.google.protobuf.ByteString
      getCompatiblePenaltyKeyBytes();

  /**
   * <pre>
   * 升舱处理类型 0. 1.
   * </pre>
   *
   * <code>int32 ProcessType = 14;</code>
   */
  int getProcessType();

  /**
   * <pre>
   * 升舱OfferToken。当UpgradeProcessType=2时有值，为直接预订升舱政策的查询的OfferToken
   * </pre>
   *
   * <code>string UpgradeOfferToken = 15;</code>
   */
  java.lang.String getUpgradeOfferToken();
  /**
   * <pre>
   * 升舱OfferToken。当UpgradeProcessType=2时有值，为直接预订升舱政策的查询的OfferToken
   * </pre>
   *
   * <code>string UpgradeOfferToken = 15;</code>
   */
  com.google.protobuf.ByteString
      getUpgradeOfferTokenBytes();

  /**
   * <pre>
   * 升舱结果答复规则；格式：A-0或者0-B；A-0，表示提交升舱后A小时告知升舱结果；0-B，表示起飞前B小时告知升舱结果
   * </pre>
   *
   * <code>string ReplyRule = 16;</code>
   */
  java.lang.String getReplyRule();
  /**
   * <pre>
   * 升舱结果答复规则；格式：A-0或者0-B；A-0，表示提交升舱后A小时告知升舱结果；0-B，表示起飞前B小时告知升舱结果
   * </pre>
   *
   * <code>string ReplyRule = 16;</code>
   */
  com.google.protobuf.ByteString
      getReplyRuleBytes();

  /**
   * <pre>
   * 升舱成功率
   * </pre>
   *
   * <code>double SuccessRate = 17;</code>
   */
  double getSuccessRate();

  /**
   * <pre>
   * 标记位
   * </pre>
   *
   * <code>int64 RestrictionFlag = 18;</code>
   */
  long getRestrictionFlag();

  /**
   * <pre>
   * 展示升舱信息标识 T:展示 F: 不展示
   * </pre>
   *
   * <code>string ShowFlag = 19;</code>
   */
  java.lang.String getShowFlag();
  /**
   * <pre>
   * 展示升舱信息标识 T:展示 F: 不展示
   * </pre>
   *
   * <code>string ShowFlag = 19;</code>
   */
  com.google.protobuf.ByteString
      getShowFlagBytes();

  /**
   * <pre>
   * 定向展示 DirectDisplay
   * </pre>
   *
   * <code>string DirectCode = 20;</code>
   */
  java.lang.String getDirectCode();
  /**
   * <pre>
   * 定向展示 DirectDisplay
   * </pre>
   *
   * <code>string DirectCode = 20;</code>
   */
  com.google.protobuf.ByteString
      getDirectCodeBytes();

  /**
   * <pre>
   * 定向隐藏 DirectBlackDisplay
   * </pre>
   *
   * <code>string BlackDirectCode = 21;</code>
   */
  java.lang.String getBlackDirectCode();
  /**
   * <pre>
   * 定向隐藏 DirectBlackDisplay
   * </pre>
   *
   * <code>string BlackDirectCode = 21;</code>
   */
  com.google.protobuf.ByteString
      getBlackDirectCodeBytes();
}
