// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com.ctrip.flight.agg.shopping.contract.message.proto

package com.ctrip.flight.agg.shopping.contract.message;

public interface DetailErrorTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ctrip.flight.agg.shopping.contract.message.DetailErrorType)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 错误Code
   * </pre>
   *
   * <code>int32 Code = 1;</code>
   */
  int getCode();

  /**
   * <pre>
   * 错误描述
   * </pre>
   *
   * <code>string Message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * 错误描述
   * </pre>
   *
   * <code>string Message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
